### ISSUE TITLE
Text missing from vector costumes

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-render#105]
Originally reported by @SillyInventor as LLK/scratch-vm#479:

### Expected Behavior

Lutin 1, 2, & 3 should have pink images of bubbles, "ok!!!", and "Hazzard!!!" respectively in https://llk.github.io/scratch-gui/#144880441/ 

### Actual Behavior

All missing.

### Steps to Reproduce

Navigate to https://llk.github.io/scratch-gui/#144880441/ 

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.87

**Comment by cwillisf** [comment]
Scratch 2.0 (expected):
![image](https://cloud.githubusercontent.com/assets/7019101/23238440/ce8790da-f916-11e6-9eeb-0ab81d503ef7.png)

Scratch 3.0 (actual):
![image](https://cloud.githubusercontent.com/assets/7019101/23238465/eac670cc-f916-11e6-9d44-5cafbd6995fb.png)

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
