### ISSUE TITLE
Changing shade switches color to a shade of red if initial color is gray scale

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#115]
Reported during internal playtest 3/3/17.

### Expected Behavior

The color should stay gray scale

### Actual Behavior

Changing shade switches color to a shade of red if initial color is gray scale

### Operating System and Browser

_Mac & Chrome_

---
Moved from LLK/scratch-gui#193
/cc @jwzimmer

**Comment by SillyInventor** [comment]
I wasn't able to replicate this on Ubuntu 16.0.1, Chrome 58.0.3029.110.
