### ISSUE TITLE
Sprite at wrong location if costume center is outside the costume box's border

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#118]
Reported via internal playtest 3/3/17.

### Actual Behavior

If costume center has been chosen outside the bounding box of the costume (as with the heart here), the sprite is placed at the wrong location.

### Example Project

- https://scratch.mit.edu/projects/67538396/#editor

### Operating System and Browser

_Mac & Chrome_

---
Moved from LLK/scratch-gui#196
/cc @jwzimmer

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
