### ISSUE TITLE
exception(Invalid offset/length when creating typed array) in ms edge browser

### ISSUE THREAD

**Issue by a49594a** [LLK/scratch-render#129]
### Expected Behavior

var pixels = new Uint8Array(Math.floor(width * height * 4));

### Actual Behavior
there is an exception: Invalid offset/length when creating typed array

RenderWebGL.js
_getConvexHullPointsForDrawable

var pixels = new Uint8Array(width * height * 4);

### Operating System and Browser
windows10, ms edge browser

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-render/pull/132
