### ISSUE TITLE
Rotation center is incorrect while sprite is scaled by "changeSize" block or "setSize" block

### ISSUE THREAD

**Issue by a49594a** [LLK/scratch-render#131]
### Expected Behavior

Rotation center should stay in the same relative location when sprite is scaled.

### Actual Behavior

The rotation center is not in the middle of the costume, the rotation center changes while sprite is scaled by "changeSize" block or "setSize" block.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
@cwillisf @rschamp Thoughts on this one?

**Comment by thisandagain** [comment]
Here is a repro case:
https://scratch.mit.edu/projects/156451053/
https://llk.github.io/scratch-gui/#156451053

**Comment by cwillisf** [comment]
Most likely I just got the order of operations wrong in the matrix math in `_calculateTransform`:
https://github.com/LLK/scratch-render/blob/develop/src/Drawable.js#L194

I'm marking this as "help wanted" -- the change probably won't require much knowledge of our codebase, though it does require an understanding of matrix math as applied to transforming geometry.

**Comment by cwillisf** [comment]
Fixed by #138
