### ISSUE TITLE
The pen gets drawn in right-angles behind the sprite when manually dragged

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-render#144]
### Expected Behavior

In Scratch 2.0, if the pen is down and you manually drag the sprite associated with it, you don't get a pen trail behind it.

When the sprite glides:
<img width="1280" alt="screen shot 2017-06-05 at 4 48 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/26802534/cd0f3688-4a0e-11e7-8a2f-45da87e1c53b.png">

When the sprite is manually dragged:
<img width="1094" alt="screen shot 2017-06-05 at 4 48 14 pm 1" src="https://cloud.githubusercontent.com/assets/1320456/26802533/cd06253e-4a0e-11e7-965b-eb0d4ed80ec9.png">

### Actual Behavior

In 3.0, I'm seeing that the pen does get drawn with the sprite, and it is drawn in very right-corner heavy lines during the drag (but not when the sprite glides or moves due to a block).

The straight lines are from the blocks; the jagged lines are from manually dragging the sprite:
<img width="1034" alt="screen shot 2017-06-05 at 4 49 06 pm" src="https://cloud.githubusercontent.com/assets/1320456/26802602/1b9ebf1c-4a0f-11e7-8a0e-a1a6628fcfdb.png">
<img width="1021" alt="screen shot 2017-06-05 at 4 45 46 pm" src="https://cloud.githubusercontent.com/assets/1320456/26802603/1ba30a4a-4a0f-11e7-8f5d-d6ceaad0f878.png">

### Steps to Reproduce

Use pen down, set pen color, and glide to compare when you drag the sprite vs. when it is moved via block in 2.0 and 3.0.

### Operating System and Browser

_Mac OS, Chrome_

**Comment by rschamp** [comment]
Do we want the pen to draw while dragging sprites? Not present in 2.0.

**Comment by cwillisf** [comment]
My vote is no. It could be fun in a few limited situations but it seems like it would add a bunch of questions in others, and I don't think it adds much "power" to Scratch programming or projects. I suspect any project that would use this feature can be implemented in another way without it.
