### ISSUE TITLE
Need API for color picking

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#158]
We need to add a public API for getting the color at an XY location. The implementation will be similar to the picking process for sprites. 

The color picking requirements are not stable yet, but it would be nice if the API could allow you to get the exact color at a point AND the pixel image data for a region around the color, so we can implement a zoomed color loupe.

**Comment by cwillisf** [comment]
I recommend looking into [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) as a possible container for returned pixel data. It stores width, height, and pixels, and it works with the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#Supported_types) so it can cross worker boundaries.
