### ISSUE TITLE
incorrect color effect for white area on phone/pad

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-render#168]
### Expected Behavior

It should work like in Desktop browser...

### Actual Behavior

When set color effect to something larger than zero (for example, 1...10...), the sprite's white area (maybe it is transparent area?) becomes black.

### Steps to Reproduce

On iPhone or Android:
1. Open llk.github.io/scratch-gui/develop
2. drag "set color effect to xxx" block in "looks" category to workspace
3. click the block to run it
4. issue as below:
![img_3909](https://user-images.githubusercontent.com/1018468/30210120-c83d419a-94cd-11e7-9c93-d3491a12e9b5.PNG)

### Operating System and Browser
It works on my Mac OS X (MacBook Air) Safari browser, and my Ubuntu Chrome browser. But failed on both my iPhone (which is Safari) and my Android tablet (in Chrome browser). So, it seems not an issue of browser but an issue of "mobile" comparing with PC???

---
Moved from LLK/scratch-gui#674
/cc @gengshenghong

**Comment by SillyInventor** [comment]
Could not reproduce on Galaxy S6 Edge, Android 6.0.1, Chrome 60.0.3112.116.

**Comment by cwillisf** [comment]
I am able to reproduce this on a Pixel 2 XL, Android 8.0.0, Chrome 62.0.3202.84
![image](https://user-images.githubusercontent.com/7019101/33535731-431c41a2-d864-11e7-9d0f-c247ad6ec566.png)

**Comment by cwillisf** [comment]
Quick repro steps:
1. Visit https://llk.github.io/scratch-gui/player.html#24542731
2. Press green flag

This project sets the color effect to 100 because I liked that shade of blue 💙

**Comment by cwillisf** [comment]
I suspect this may be an issue with certain graphics chips (GPUs). Here's what we know so far:

❌: Affected by this issue (the white areas on the cat become black)
✔️: Not affected by this issue (the white areas on the cat stay white)

Device | GPU | Results | Reported by
-- | - | - | -
Windows laptop | Intel HD 4600 | ✔️ | @cwillisf
Mac laptop | Intel Iris Plus 640 | ✔️ | @cwillisf
Galaxy S6 Edge | Mali-T760 MP8 | ✔️ | @SillyInventor 
Pixel 2 XL | Adreno 540 | ❌ | @cwillisf
iPhone (model?) | PowerVR (model?) | ❌ | @gengshenghong
Android tablet (model?) | ??? | ❌ | @gengshenghong
iPad MH312LL/A | PowerVR Series 6XT GXA6850 | ❌ | @cwillisf
