### ISSUE TITLE
Collisions output "undefined" when outside of another sprite's costume

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-render#169]
### Expected Behavior

The tests in [this project](https://llk.github.io/scratch-gui/develop/#174192013) should output the same results as they do in 2.0 (see the browser console in 3.0).

~~Also worth discussing (but perhaps in a separate issue) is what the expected results should be in general; [this user](https://scratch.mit.edu/discuss/topic/276337/) ran into a problem when made a sprite "Wall" whose costume was a hollow box, and the "touching" block on a sprite inside of the rectangle (not touching its edges) returned true. To make things weirder, in vector costumes, this *isn't* a problem; note my "Inside vector" test returns false, whereas "Inside bitmap" returns true.~~

^ This is a bug with the Scratch 2.0 paint editor; the rectangle tool actually paints [not-quite-transparent shapes!](https://scratch.mit.edu/projects/174254705/)

### Actual Behavior

Collisions against another sprite when the sprite is *outside* of the other sprite should return false, not undefined.

Complete test results on 3.0:

![Test results](https://user-images.githubusercontent.com/9948030/30326924-949dbf42-97a0-11e7-9aaa-b2b4799028f3.png)

### Steps to Reproduce

1. Open the above project and run the tests.
2. Open the browser console to see the output of the "say" blocks.
3. Compare the 3.0 results with the 2.0 results ("2.0:").

### Operating System and Browser

The project was ran with both 2.0 and 3.0 in Linux (Debian Testing), Firefox 52.0, and Flash 26.0 (for 3.0).

**Comment by cwillisf** [comment]
Looks like this has been fixed. Thanks for the great test case!
