### ISSUE TITLE
Say and think bubbles

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#18]
In Scratch 2.0, these are layered with the sprite itself and positioned according to a bounding box calculated according to what's "actually in" the sprite. E.g., if you start with the cat and run "say Hello", and then edit the cat costume to draw a line in the upper right corner, the say bubble moves:
<img width="278" alt="screen shot 2016-07-13 at 4 42 07 pm" src="https://cloud.githubusercontent.com/assets/120403/16819080/c0de2916-4918-11e6-9403-9b2f2942c216.png">

**Comment by dekrain** [comment]
I think it can be based on #48
