### ISSUE TITLE
Variable and list monitors

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#19]
We need to make a choice at some point who is responsible for these (the "Scratch" wrapper or the renderer itself). One argument for doing it in the renderer is the layering question. In Scratch 1 and 2, monitors can be layered with the other sprites in the project, and they are often used as a UI element (e.g., a score readout).

**Comment by tmickel** [comment]
Think it might be helpful for VM development to have these, too. Might do a prototype version unless anyone is opposed.

**Comment by liam4** [comment]
Argument for doing it with "Scratch" wrapper - watcher can be placed anywhere on the screen at all, e.g. in the workspace. But it can't be layered like you could using the renderer.

However I do think that either way the information that the watchers should display should be gotten from the VM (not the actual UI layout though of course!).

**Comment by chooper100** [comment]
For discussion:
A while ago for 2.0, the possibility of keeping variable and list watchers always at top was discussed.

I believe that, if we were to implement that, now would be the time.

(imo I think it is good being able to put sprites above watchers. Changing this would also introduce compatibility issues which we want to avoid)

**Comment by paulkaplan** [comment]
First iteration of this is going to happen in the GUI, tracked in issue https://github.com/LLK/scratch-gui/issues/326
