### ISSUE TITLE
Improve stamp performance

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-render#190]
### Expected Behavior

Take less than a millisecond, or better, to stamp onto a PenSkin.

### Actual Behavior

Easily takes 10s of milliseconds to execute a single stamp block.

### Steps to Reproduce

https://scratch.mit.edu/projects/173918262/

### Operating System and Browser

Mac OS 10.12 Chrome (likely most)

**Comment by mzgoddard** [comment]
`stamp` uses `readPixels` to read from the GPU. `readPixels` works against gpu performance by stalling the gpu and reversing the direction of output so the CPU can read from it. `stamp` can probably be speed up by doing all of its work on the GPU by rendering to WebGL RenderBuffers instead of reading through `readPixels`, setting a canvas with the output, and drawing that canvas to the PenSkin canvas (which then needs to update the texture in WebGL).

**Comment by mzgoddard** [comment]
Related to https://github.com/LLK/scratch-vm/issues/741

**Comment by CatsAreFluffy** [comment]
I think it's strange that the stamp block has a special internal function for itself.

**Comment by rschamp** [comment]
Fixed in #319
