### ISSUE TITLE
Improve `pick` performance

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-render#191]
### Expected Behavior

Take less than a millisecond, or better, to pick a drawable from a given x, y position.

### Actual Behavior

On a Samsung Chromebook Plus a single pick can take 10s of milliseconds to execute. (Hard to tell actual performance cause the calls take so long it can bleed into the recorded time for the next pick operation.) The underlying `readPixels` method is also known to have a poorly defined execution time due to its behaviour.

### Steps to Reproduce

Projects like https://scratch.mit.edu/projects/130041250/ use pick to test if the Drawable is touching the mouse-pointer. Once that project has created all its clones, each clone tests if its touching the mouse-pointer, leading to frame times from **250 ms** (milliseconds) to **350 ms**.

### Operating System and Browser

All

**Comment by mzgoddard** [comment]
Related to https://github.com/LLK/scratch-vm/issues/738

**Comment by mzgoddard** [comment]
One probable replacement implementation would be to store data from all the points `_getConvexHullPointsForDrawable` builds to than build the convex hull. Testing for the "picked" drawable could transform from world space to Drawable space through the Drawable transform and then align with the closest pixel from the convex hull data (or multisample) to determine if that Drawable is picked. Instead of drawing all the candidates they could be iterated in the reverse drawing order, as in from the top drawable to the bottom.

The convex hull point data could be possibly stored in an object called a `PointShape` and have a pick method to separate its logic out into a testable object.

Performance for this would then rely on `_getConvexHullPointsForDrawable` when the convex hull is invalidated. Outside of that invalidation this should be pretty quick.

**Comment by rschamp** [comment]
Fixed in #196
