### ISSUE TITLE
Improve `_getConvexHullPointsForDrawable` performance

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-render#192]
### Expected Behavior

Take less than a millisecond, or better, to create a convex set of points containing the drawable's shape.

### Actual Behavior

`_getConvexHullPointsForDrawable` currently has performance like [`pick`](). It renders the drawable to the webgl buffer and reads back with `readPixels` which busy waits for the GPU to stop what its doing and read out the requested state to the CPU. This takes milliseconds to 10s of milliseconds depending on the running hardware.

### Steps to Reproduce

Open a project that uses `if on edge, bounce` like https://scratch.mit.edu/projects/130041250/. When a drawable is created or any change to the drawable invalidates the convex hull, and its owning target executes `if on edge, bounce` it needs to build a new convex hull. The linked example project encounters this issue while it creates 50 clones at the beginning.

Before https://github.com/LLK/scratch-render/pull/188 is merged, its especially clear the `_getConvexHullPointsForDrawable` performance is like. As it creates the clones, the fixed bug in #188 causes every clone to rebuild its hull every frame a clone is created. Leading up to 50 clones, the last frame can lapse into a full second for some hardware.

### Operating System and Browser

All

**Comment by mzgoddard** [comment]
Related to https://github.com/LLK/scratch-vm/issues/738

**Comment by mzgoddard** [comment]
Building on https://github.com/LLK/scratch-render/issues/191#issuecomment-342862720, `pick` and `_getConvexHullPointsForDrawable` could work with a Shape class that contains the alpha channel of a skin. With an alpha channel Shape, the Drawable's model transform, and the effect texture coordinate math in the shader (rewritten in js with twgl), `_getConvexHullPointsForDrawable` can build the points on the CPU with JS and not have to wait for the GPU to stop itself and read back to us.

**Comment by rschamp** [comment]
Fixed in #196
