### ISSUE TITLE
Sprite touching sprite

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#20]
IIRC, all of Scratch's current queries are possible right now, except the one for "sprite touching sprite." Haven't thought about how to implement this myself, but thought it was worth raising.

**Comment by tmickel** [comment]
Maybe we can associate a `groupType` with each Drawable that you can set. And then add `touchingGroupType(drawableId, groupType)`. On the VM side, we generate a unique ID for each sprite, and all of its clone drawables are given that groupType ID.

**Comment by liam4** [comment]
I'm thinking `touchingGroupType` should probably use a more abstract `touchingDrawable` (id), too - might be handy for any mods that might like to make first class (references to specific) sprites!

**Comment by tmickel** [comment]
Yep, thinking on this longer, might be best to do: `RenderWebGL.prototype.isTouchingDrawables = function(drawableID, candidateIDs)` which would be simpler and require no additional state tracking of groups.
