### ISSUE TITLE
Touching color should work when sprites are not visible

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#212]
From @towerofnix 

---
Expected (2.0) Behavior
"Touching color" returns true when the sprite overlaps the given color, regardless of whether or not the sprite is hidden. "Touching sprite" returns true if the sprite overlaps the other sprite, and the sprite is shown; if it is hidden, "touching sprite" returns false.

Actual Behavior
"Touching color" returns false when the sprite is hidden. "Touching sprite" behaves as described in 2.0.

Steps to Reproduce
Demo project: 2.0, 3.0. Move the sprite around using the mouse, and use the space bar to toggle the sprite between being shown and hidden. Observe the contents of the speech bubble while dragging.

(Note - in the speech bubble that shows up, you can see that, next to "touching (sprite)", sometimes "undefined" is being said instead of "false".. undefined is a falsey value, so this is okay, but maybe something to look into if it's not already reported somewhere..)

I don't know what the expected behavior is, but I would think that this incompatibility could be a source of issues in platformer projects?

Demo project 2: 2.0, 3.0. Notice how, in Scratch 3.0, when you hide the sprite, it falls through the floor! 🕳

Operating System and Browser
Firefox Nightly (59) on Debian Testing. I'm fairly certain this same bug was reported here.

**Comment by paulkaplan** [comment]
Eek here are 4 cases I tested. 

|                 | Hidden       | Ghost 100 |
|-----------------|--------------|-----------|
| Touching sprite | not detected | detected  |
| Touching color  | detected     | detected  |

In scratch 2
![image](https://user-images.githubusercontent.com/654102/33773576-5fa9887a-dc06-11e7-9ba2-216aac6c163d.png)

In scratch 3
![image](https://user-images.githubusercontent.com/654102/33773718-d0575d2c-dc06-11e7-94d2-11d5021fc79e.png)

**Comment by towerofnix** [comment]
Broken demo project links in the original post btw: demo 1 in [2.0](https://scratch.mit.edu/projects/191930440/#editor), [3.0](https://llk.github.io/scratch-gui/#191930440), demo 2 in [2.0](https://scratch.mit.edu/projects/191931857/#editor), [3.0](https://llk.github.io/scratch-gui/#191931857).

**Comment by paulkaplan** [comment]
Cool thanks, verified with the falling cat project. 

Also added a commit to fix the `undefined` issue. That was a good catch, wouldn't have noticed because of the falsey-ness, but definitely should be `false`. 

![sensing-report--2](https://user-images.githubusercontent.com/654102/33777973-cc5d5ad8-dc14-11e7-9a30-ba400769aee4.gif)
![sensing-report--3](https://user-images.githubusercontent.com/654102/33777976-cd8048ee-dc14-11e7-95d9-e32bfd9da499.gif)
