### ISSUE TITLE
Fail gracefully if WebGL isn't available

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-render#220]
### Expected Behavior

Renderer should check whether WebGL is available and fail gracefully if it isn't

### Actual Behavior

Fatal errors in the console

### Steps to Reproduce

Run the GUI on a machine or browser that doesn't support WebGL, examples:
- old samsung chromebooks
- old macbook Air Jamaica

**Comment by CosmicWebServices** [comment]
Why not fall back to html5 using a library?

**Comment by chrisgarrity** [comment]
GUI currently catches fatal errors and checks for WebGL. Should the renderer check for webGL and raise its own fatal error (this will still get caught in GUI), or something else? 

/cc @cwillisf
