### ISSUE TITLE
Spotlight stage backdrop looks different on stage/thumbnails vs in the paint editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#236]
### Expected Behavior

They should look the same

### Actual Behavior

The gradients on the spotlights are being interpreted differently by the renderer
![image](https://user-images.githubusercontent.com/2855464/35300182-b988d486-0055-11e8-9265-a7f65650934e.png)

The paint editor's interpretation looks more like Scratch 2's interpretation
![image](https://user-images.githubusercontent.com/2855464/35300263-ed63c9f0-0055-11e8-8627-a27bc3ad9453.png)

To keep the renderer and paint editor consistent, maybe SVGs should be preprocessed through paper.js?

### Steps to Reproduce

Add spotlight-stage2 as a backdrop

### Operating System and Browser

Windows 10 Chrome

**Comment by thisandagain** [comment]
@fsih Would you mind scheduling a meeting for us to discuss this item as well?
