### ISSUE TITLE
Shapes have fuzzy black outlines on stage

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#237]
### Expected Behavior

White shapes without outlines should have no outlines

### Actual Behavior

White shapes have fuzzy black outlines on the stage
![image](https://user-images.githubusercontent.com/2855464/35415484-cb9859d6-01f3-11e8-83b6-e034ead747d0.png)

### Steps to Reproduce

Draw some white things in the paint editor and observe them on the stage.
I think this is happening for non-white shapes too, it's just harder to tell
![image](https://user-images.githubusercontent.com/2855464/35415641-52f81eb6-01f4-11e8-9c5f-b2427933a675.png)

### Operating System and Browser

Windows 10 Chrome

**Comment by cwillisf** [comment]
This might have to do with alpha blending (transparency) being processed twice: once when the SVG is being rasterized by `scratch-svg-renderer`'s `_draw` method and again when drawn to the stage by `_drawThese`. I'm sure premultiplied alpha plays a role as well: the darkened pixels are probably being darkened by an amount proportional to their alpha value. See also: https://microsoft.github.io/Win2D/html/PremultipliedAlpha.htm

**Comment by cwillisf** [comment]
Another possibility: there may be a step in the rendering process where we need to clear to transparent white (RGBA = 1,1,1,0) rather than transparent black (RGBA = 0,0,0,0).

**Comment by gnarf** [comment]
@cwillisf - @mzgoddard and I suspect this might be a problem with premultiplied alpha also, maybe we update the blend mode to SRC_ALPHA and not premultiply like we did in the stamp routines?

**Comment by fsih** [comment]
Possibly related:
https://github.com/LLK/scratch-render/issues/110
https://github.com/LLK/scratch-gui/issues/1894

**Comment by fsih** [comment]
This issue looks like it's gone now. @thisandagain can you check the project you mentioned in https://github.com/LLK/scratch-gui/issues/4103 ?

**Comment by fsih** [comment]
From @adroitwhiz 
An alpha-multiplication-related dark fringe appears around costumes whose textures are linearly resampled, as seen in [this project](https://scratch.mit.edu/projects/311778332/)

I believe the underlying problem is discussed in the article [GPUs prefer premultiplication](http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/)--canvas image data is not premultiplied, and must be premultiplied before being sampled.

**Comment by adroitwhiz** [comment]
Now that #480 has gone in, linear interpolation is being used on vector skins a lot more, and people are complaining about this bug on the Bugs and Glitches forum:

- ["Vector graphics on Scratch isn't looking that good."](https://scratch.mit.edu/discuss/topic/377208/)
- ["Fix vector!"](https://scratch.mit.edu/discuss/topic/376886/)
