### ISSUE TITLE
Blank (0x0) vector costumes cause WebGL errors

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#239]
Projects like this that have a 0x0 vector costume cause a bunch of errors and warnings:

https://llk.github.io/scratch-gui/develop/#157775904

![image](https://user-images.githubusercontent.com/654102/35686290-f23c1974-0739-11e8-921a-d0b1754f6067.png)

In that project the uncaught error doesn't seem to cause any actual issues, but uncaught errors are still worrying.

The costume in this case is this:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="2" height="2" viewBox="-1 -1 2 2"> 
<!-- Exported by Scratch - http://scratch.mit.edu/ --> 
</svg>
```

**Comment by fsih** [comment]
Merging into #242
