### ISSUE TITLE
SVG re-rasterization for varying sizes

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#24]
We've talked about this at some point. Currently, when you scale up a sprite, it gets blurry. I think this is because the SVG rasterization only happens once, while it needs to happen either on resize, or generate multiple sizes at the beginning.

**Comment by paulkaplan** [comment]
This is a good demo project for that 

https://scratch.mit.edu/projects/113396270/
https://llk.github.io/scratch-gui/develop/#113396270

![image](https://user-images.githubusercontent.com/654102/32784125-eef9d1d6-c91b-11e7-9a73-8e250885df3b.png)

**Comment by paulkaplan** [comment]
Just wanted to leave another test case here: 
![image](https://user-images.githubusercontent.com/654102/33996917-a8a4d68e-e0b0-11e7-9bef-99d7a191f058.png)
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#10015060

@thisandagain @cwillisf Do you think we should escalate this issue, even to just figure out how we plan on fixing this in the future?

**Comment by thisandagain** [comment]
@paulkaplan Yeah. I think we should escalate this even it is just means a few of us get together to devise a strategy and make sure it is on the roadmap.
