### ISSUE TITLE
Color effect inverts colors on iPad 

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#245]
### Expected Behavior

Sprites change color when color effect is changed

### Actual Behavior

Colors get inverted
**Before**
![d1485480-352a-4d7c-8aa7-69496e1ab913](https://user-images.githubusercontent.com/31634240/37255313-245501aa-2521-11e8-9d8b-bf648be60ab4.jpeg)
**After**
![c3576a59-a4d2-453b-975b-3b0972deb177](https://user-images.githubusercontent.com/31634240/37255328-592aaa38-2521-11e8-9af6-ad8b822e031c.jpeg)

### Steps to Reproduce

Change the color effect on an iOS device 

### Operating System and Browser

iOS 11.1 Chrome 64

---
Moved from LLK/scratch-gui#1605
/cc @kyleplo

**Comment by mrjacobbloom** [comment]
As @Clark-E mentioned in the original issue, it might have to do with the epsilon thing from #168 / #210

**Comment by rachel-fenichel** [comment]
I saw one report that might have been this on a Chromebook ("i drew a picture and the colours are in reverse on stage").

**Comment by thisandagain** [comment]
@rachel-fenichel Hmm! Thanks for the additional info.
