### ISSUE TITLE
When Backdrop Clicked doesn't register when clicking on a blank section of a backdrop

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-render#249]
Expected Behavior
Clicking the stage somewhere there is no art should result in the When Stage Clicked block activating.

Actual Behavior
If a backdrop of the sprite has an area that has no art in it and you click that part on the stage the When Stage Clicked block doesn't activate.

Note: This is not the case when the default costume is used for the stage, but is the case if you paint a new backdrop or if you modify the default backdrop.

Repro Steps
Open a new Scratch 3.0 project
Select the stage
Click the costumes tab
Draw a shape in the editor.
Click back to blocks
Build a stack that is When Stage Clicked > Play Sound Pop
Click the stage where it is white
Note: the lack of a pop sound
Click the stage in a part that you have added a shape
Note: A pop!

Paul asked me to bring mention his to @cwillisf

**Comment by kchadha** [comment]
When stage clicked also doesn't register when clicking on a pen line on the stage. In Scratch 2.0, it does.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#1668
