### ISSUE TITLE
Sprite flashing/highlighting

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#25]
We may need some plan about how to highlight a drawable when it's clicked in the editor, like this:
![sprite-flash](https://cloud.githubusercontent.com/assets/120403/17228465/1809e512-54e1-11e6-84be-ce43b53c03ab.gif)
It's pretty useful to see which sprite is which.

**Comment by tjvr** [comment]
Oh, wow. I didn't know you could do that!

**Comment by paulkaplan** [comment]
https://github.com/LLK/scratch-render/issues/127 is the same as this, but was triaged more recently, so i'm closing this one and tracking it there.
