### ISSUE TITLE
Stretched lines render differently in scratch 2.0 and scratch 3.0

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-render#255]
### Expected Behavior

![image](https://user-images.githubusercontent.com/13686399/38697306-6f6de1dc-3e46-11e8-9017-6a399b76e167.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13686399/38697321-784ea2aa-3e46-11e8-98a4-3c32eafbbd89.png)

### Steps to Reproduce

Open https://scratch.mit.edu/projects/215620314/ and https://preview.scratch.mit.edu/#215620314

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/381
