### ISSUE TITLE
Performance - Slows down Firefox a lot while open

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-render#26]
While running in Chrome (Canary, 54) it works fine and at the speed it should. But in Firefox (Nightly, 51), it strongly lags the entire browser. I'm not sure why, but these errors that only appear in Firefox's console might have something to do with it:

```
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow. (render.js:13794:10)
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow. (render.js:13794:10)
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401
```

I'd test it in Safari as well, but the browser doesn't want to open for me.. :/

Aside from that I'm on a late 2013 iMac running OS X El Capitan 10.10.4.

**Comment by tmickel** [comment]
Thanks for the report. We'll check this out. Have you also tried in Firefox's release (non-nightly/beta) version?

**Comment by liam4** [comment]
Yeah, I get the same issue on the latest release of Firefox 48.

**Comment by CosmicWebServices** [comment]
I think that this is a firefox/webgl issue not a scratch-render issue

**Comment by liam4** [comment]
Well, you'll be glad to know that this isn't an issue in Firefox 52 (nightly).

Which isn't being released until early 2017, but conveniently that's before - as far as I know - any proper release or "public" alphas of this..

**Comment by bobbybee** [comment]
See the discourse at https://github.com/mrdoob/three.js/issues/9109

**Comment by towerofnix** [comment]
The current major version of Firefox is 52, so this isn't a problem now. I'm not certain what Scratch 3.0's supported browsers are, though; if it's aiming for 51 or earlier, this might still be an issue (I don't have 51 to see if this is still an issue anyways).

**Comment by paulkaplan** [comment]
Closing this as Firefox is now 5 major versions beyond 51.
