### ISSUE TITLE
SVGs with text appear not to render

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#28]
For example, try opening project 96384969.

**Comment by tmickel** [comment]
Maybe we'll want to use something like canvg (https://github.com/canvg/canvg), what Phosphorus uses? Or something similar but better?

**Comment by tmickel** [comment]
Or maybe we'll be best off reproducing these:
https://github.com/LLK/scratch-flash/tree/master/src/svgutils

Even Phosphorus seems to render many SVGs a lot different from Scratch 2.0 :(

**Comment by tmickel** [comment]
Other than canvg, we could be working off of Fabric, which has a pretty full-featured SVG renderer:
http://fabricjs.com/test/svg_import/

and could be used to manipulate them in a paint editor, too...

**Comment by tmickel** [comment]
Hmm, fabric.js doesn't seem to render some Scratch text...not sure why.

**Comment by CosmicWebServices** [comment]
@tmickel Did you make an issue on fabric.js?

**Comment by tmickel** [comment]
@CosmicWebServices not yet - maybe if we figure out why it doesn't work :) It's also possible our actual Scratch SVGs are broken...

**Comment by CosmicWebServices** [comment]
@tmickel they may be able to figure out why it is broken

**Comment by CosmicWebServices** [comment]
I will look through the code soon see if I can possibly figure it out.

**Comment by tmickel** [comment]
Possibly partially addressed by #56.

**Comment by tmickel** [comment]
Looks largely addressed in #56, will open more specific issues for text rendering if/when they come up.
