### ISSUE TITLE
Multiple spaces and newlines in a row in text are not preserved in the renderer

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#292]
### Expected Behavior

Paint and render should look the same

### Actual Behavior

Render does not preserve multiple spaces or newlines in a row

### Steps to Reproduce

Make a text box with multiple spaces or newlines in a row
<img width="1220" alt="screen shot 2018-05-23 at 17 40 14" src="https://user-images.githubusercontent.com/2855464/40452643-8ad1b360-5eb0-11e8-8c3a-82620ed0f3cb.png">

### Operating System and Browser
Mac Chrome

**Comment by cwillisf** [comment]
See also:
https://stackoverflow.com/questions/25361697/how-to-preserve-spaces-in-svg-text
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by fsih** [comment]
Example from https://github.com/LLK/scratch-paint/issues/763

https://scratch.mit.edu/projects/261570023
https://beta.scratch.mit.edu/#261570023

**Comment by fsih** [comment]
Another example
https://scratch.mit.edu/projects/56534898/

2
<img width="481" alt="screen shot 2018-12-18 at 15 40 28" src="https://user-images.githubusercontent.com/2855464/50181765-475ecf80-02db-11e9-8961-39c646ace337.png">
3
<img width="426" alt="screen shot 2018-12-18 at 15 41 13" src="https://user-images.githubusercontent.com/2855464/50181805-5e052680-02db-11e9-9d1b-26c807f74b2b.png">

**Comment by fsih** [comment]
Just noticed that Scratch 2 doesn't display spacing in text the same on stage vs in paint either :p
<img width="804" alt="screen shot 2018-12-18 at 16 55 50" src="https://user-images.githubusercontent.com/2855464/50185459-d1ac3100-02e5-11e9-80bc-641379309962.png">
