### ISSUE TITLE
Blurry when dragging - Extract drawable doesn't respect pixel ratio

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#294]
### Expected Behavior

_Please describe what should happen_

`extractDrawable` should return image data that is appropriately scaled for the current devicePixelRatio. 

### Actual Behavior

_Describe what actually happens_

Currently it always returns imagedata rendered at 1x, causing things that use `extractDrawable` to be blurry on hi dpi screens (e.g. editor-style dragging in scratch-gui)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Using a hi dpi screen, see how extractDrawable looks, either in production (by dragging a sprite on https://llk.github.io/scratch-gui/develop) or the playground.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Hi DPI screen, tested on modern retina macbook.

---

/cc @cwillisf. I'm not sure what you think the best way to deal with this is. I was able to fix it pretty simply by scaling the drawable bounds width/height in the calls to `gl.viewport`, the creation of the imageData, the `gl.readPixels` call and the width/height properties of the returned object. The "scale" of the returned imageData should probably be included with the `DrawableExtraction` object. Does that sound reasonable?

**Comment by evhan55** [comment]
Can confirm I see this too on MacBook Pro (Retina, 15-inch, Mid 2015).

Whenever https://github.com/LLK/scratch-render/pull/376 I can try to look at it since I was just working in that area.
