### ISSUE TITLE
createDrawableWithProperties?

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#30]
I've noticed this problem with the VM-renderer combo:
- VM creates a clone of a sprite. A drawable is immediately requested with `createDrawable`, and a callback is attached.
- Execution of blocks proceeds, possibly for ~2/3*16ms, blocking any response from the callback.
- On return from the callback, the clone immediately sets its properties (x, y, skin, etc.)

Basically, a full frame passes between when we can tell the renderer to make a drawable, and when we can tell it what to put into it. Pretty sure this is at least part of what's leading to lots of squirrels:
<img width="353" alt="screen shot 2016-09-08 at 5 13 55 pm" src="https://cloud.githubusercontent.com/assets/120403/18367143/aa0a9ce6-75e7-11e6-88fc-85ad81e54b5d.png">
That might also be a problem with reloading the costume, not sure.

**Comment by tmickel** [comment]
We can probably forget about this if we do `createDrawable` synchronously, agreed @cwillisf ?

**Comment by cwillisf** [comment]
I agree that it seems unnecessary in a synchronously-rendered world, but if it's what the VM usually wants to do then it couldn't hurt to make it easier.

> Pretty sure this is at least part of what's leading to lots of squirrels

:shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by tmickel** [comment]
Sounds good. Would be happy to have the functionality in but definitely not urgent in any way, then!
