### ISSUE TITLE
Story costumes are scaled up and cut off

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#311]
### Expected Behavior
The story costumes should look like the preview

### Actual Behavior
The story costumes are a corner of themselves on stage
<img width="1258" alt="screen shot 2018-07-12 at 19 42 17" src="https://user-images.githubusercontent.com/2855464/42665043-e48b966e-860b-11e8-91b0-3a27357f410e.png">

### Steps to Reproduce
1. Go to costumes tab
2. Add a costume from the library. (NOT sprite)
3. Scroll alllll the way down and choose one of the letters

### Operating System and Browser
Mac Chrome

**Comment by kyleplo** [comment]
Can't reproduce on Windows Chrome

**Comment by thisandagain** [comment]
Unable to reproduce on Windows Chrome, MacOS Chrome, or MacOS Firefox
