### ISSUE TITLE
Radial gradients look weird on iOS Safari

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-render#313]
### Expected Behavior

Radial gradient looks the same way it does in Scratch 2.0.

### Actual Behavior

It has this weird shiny thing in the middle.

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/develop/#236165720 on an iPad and look at the Sun sprite. In the thumbnail of the sprite and the paint editor, it looks normal but on the stage it looks weird.

### Operating System and Browser

iPad Pro, iOS 11, Chrome (not sure of version)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-render/issues/315
