### ISSUE TITLE
[Windows/Firefox] On list monitor, there's a space after "w"

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-render#317]
### Expected Behavior
No space expected

### Actual Behavior
Strange Space! (see at full screen mode)
![](https://screenshotscdn.firefoxusercontent.com/images/d39c7a75-180d-4555-b5c8-6db44fcc3351.png)
will when between

### Steps to Reproduce
1. Open https://scratch.mit.edu/projects/230003247/#fullscreen
2. Open https://llk.github.io/scratch-gui/develop/#230003247 and go to fullscreen mode

### Operating System and Browser
Windows 7 HomePremium 64bit SP1
Firefox 61.0.1

**Comment by paulkaplan** [comment]
Hmm can't repro in Mac/Chrome, Mac/Safari or Mac/Firefox. Looks like a Windows font rendering issue :(

**Comment by kyleplo** [comment]
Can't repro on Windows 10 Chrome or Firefox

**Comment by apple502j** [comment]
Still can repro.
![](https://screenshotscdn.firefoxusercontent.com/images/7bbdf678-e9b7-44f6-bd1f-45ec180e5f14.png)

**Comment by apple502j** [comment]
Fixed anyway?
