### ISSUE TITLE
List monitors don't wrap to the next line

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-render#324]
### Expected Behavior

Long items should wrap to the next line:
![image](https://user-images.githubusercontent.com/31634240/43318730-eb819ddc-916f-11e8-856f-5a6a1c0f0bb1.png)

### Actual Behavior

They don't:
![image](https://user-images.githubusercontent.com/31634240/43318742-fa6528be-916f-11e8-8fd1-08e40659bd41.png)

### Steps to Reproduce

Create a list with a long item.
### Operating System and Browser

Windows 10 Chrome 67

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#2744
