### ISSUE TITLE
Visual artifacts between opaque and transparent portions of (pen)canvas

### ISSUE THREAD

**Issue by Robomandude** [LLK/scratch-render#338]
### Expected Behavior
Drawing a black pen over a black backdrop should not produce any noticeable change.

### Actual Behavior
Doing this produces a thin gray-ish outline around the pen
The artifacts only appear where transparent parts of the canvas meet opaque parts of the canvas.
### Steps to Reproduce

Set the backdrop to solid black
Draw some black pen

Possibly related to issue #306  

Compatibility testing page: 
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#240420237

### Operating System and Browser
Windows 7  Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
I'm fairly certain that this is the same as https://github.com/LLK/scratch-render/issues/306. Closing this for tracking there, but will keep this around for reference.
