### ISSUE TITLE
Infinite loop in WebGLRenderer

### ISSUE THREAD

**Issue by mraerino** [LLK/scratch-render#344]
### Expected Behavior

When loading a sprite, it is displayed and can be used.

### Actual Behavior

When loading a sprite, the renderer will sometime get into a infinite loop and cause the tab to become unresponsive. The sprite is already displayed at that time.

### Steps to Reproduce

I was loading [this svg](https://gist.github.com/mraerino/ec23aa4ae759f4719f4cc0342932faad) into scratch-paint when the browser became unresponsive. This also happend with JPGs and other SVG sprites before.
When pausing Javascript, the browser was stuck at `RenderWebGL.js:962`. The `bounds` constant in that function had these values:
```
{
  bottom: -Infinity
  left: Infinity
  right: Infinity
  top: -Infinity
}
```

### Operating System and Browser

MacOS 10.13.6 / Chrome 69

---

**Note:**
I will try to find the cause of the bug myself, since we are basing a project on scratch-gui and need a fix soon, but already wanted to let you know about it. So you can probably expect a pull-request for this.

**Comment by thisandagain** [comment]
Resolved in #349
