### ISSUE TITLE
Remove worker infrastructure

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#35]
Does this sound right:

1. Remove RenderWebGLWorker.js
2. Remove index-webworker.js
3. Remove index-web.js?
4. Remove WorkerMessages.js
5. Remove RenderWebGLLocal.js ? Should we have index.js export RenderWebGL instead?
6. Remove worker handlers here: https://github.com/LLK/scratch-render/blob/develop/src/RenderWebGL.js#L464
7. Remove render-worker.js, render-worker.min.js and references in webpack.config.js

**Comment by tmickel** [comment]
Assigning @cwillisf for confirmation - happy to do it myself though!

**Comment by cwillisf** [comment]
Sounds pretty good, with the exception that some or all of `RenderWebGLLocal.js` will need to be merged into `RenderWebGL.js`. Roughly speaking, `RenderWebGLLocal.js` contains the renderer's public methods whereas `RenderWebGL.js` contains private/protected methods.

**Comment by tmickel** [comment]
Hmm, ok. Do you think it's better to keep it around then, as the public interface?

**Comment by cwillisf** [comment]
I could see that going either way. The functions are generally of the form "run one or two lines of code and return a Promise object wrapping the results" so in some ways it feels a bit silly to keep it around if the motivation for that style of API is going away. On the other hand, if we want to stick with the `Promise`-based interface then maybe we should keep it.
Do you have opinions on whether or not you'd like the VM to keep using `Promise` objects to interact with the renderer?

**Comment by tmickel** [comment]
Hmmm, yeah. I think my opinion is that we should only return `Promise`s if something is actually happening asynchronously. In theory I guess we could still have the renderer do some async operations (...although none come to mind...). And I think the VM should continue to know how to deal with promises, for things like devices, etc.

So for now I think get rid of `RenderWebGLLocal` and fold everything into `RenderWebGL`.

Let me know if you have further thoughts - else I'll get to work on this sometime soon!
