### ISSUE TITLE
Should `updateProperties` be split into multiple functions?

### ISSUE THREAD

**Issue by mzgoddard** [LLK/scratch-render#364]
`updateProperties` is called with all properties once (when a target is created) and other times with one or two properties. Would the Scratch's performance benefit from have a few of these single or double member `updateProperties` uses cases being split into their own functions?

These functions should benefit from not needing to check what is in the properties object. They should be able to know the specific properties they will receive. Some benefit may be gained by reducing the size of those more specific functions making them more likely to be further optimized by a JS engine. As well we may be able to reduce the call stack size and save time by calling less functions.

In the cases of single property `updateProperties` calls, `updateProperties` itself may be able to call those directly to possibly reduce new code duplication.

**Comment by fsih** [comment]
We did it

**Comment by fsih** [comment]
There's still cleanup though
