### ISSUE TITLE
Mosaic Effect causes mouse to touch sprites while not over the sprite

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-render#366]
### Expected Behavior

When you add the mosaic effect to a sprite it should only trigger the Touching Mouse Pointer block when the mouse is over the sprite.

### Actual Behavior

If you set the mosaic effect to any number greater than 0, Scratch will consider the mouse to be over that sprite as if it existed "mosaiced" at full size infinitely far to the right and below the actual space the sprite is located in.

![mosaicbroken](https://user-images.githubusercontent.com/1088291/47749719-1ad7f100-dc64-11e8-8321-ef08b22eba55.gif)

This only affects the mouse pointer and not other sprites.   Setting the it so it says `If touching [other sprite]` doesn't trigger the if statement if the other sprite is 

You can see this in this project: https://llk.github.io/scratch-gui/develop/#13911786

### Steps to Reproduce

In a new project build this stack on the cat:
![screen shot 2018-10-30 at 4 52 20 pm](https://user-images.githubusercontent.com/1088291/47749768-36db9280-dc64-11e8-898c-8f08f4238ca9.png)

Drag a `Set Mosaic Effect To` that is set to any number > than 0 onto the workspace
Click the green flag

Run the Set Mosaic Effect block
Move the mouse around the stage
Note: the color changes on the sprite when the mouse is lower and to the right of the sprite.
Note: It also stops at some points corresponding with gaps if the sprite were tiled.

While the sprite is changing color click and drag
Note: the sprite moves as if you were dragging it.

Move the mouse into the sprite area below the stage
Note: the cat will change color while down there.

### Operating System and Browser

Mac Chrome

**Comment by fsih** [comment]
Neat!

You can drag the sprite from the infinite void too!

**Comment by kchadha** [comment]
It looks like this is also a problem with `when this sprite clicked`

![mosaic-when-this-sprite-clicked](https://user-images.githubusercontent.com/1786240/50522810-d23d8800-0a9a-11e9-952f-7f1326d5e313.gif)

**Comment by ktbee** [comment]
Fixed by https://github.com/LLK/scratch-render/pull/424
