### ISSUE TITLE
Speech bubbles are left-aligned, not center-aligned as in 2.0

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-render#368]
Not a bug report exactly, but just a difference I noticed. In 2.0, speech bubbles are center-aligned:

![Two Scratch cats with speech bubbles containing center-aligned text; one saying "A.", the other "I love this incorporating an amusement park into our day."](https://user-images.githubusercontent.com/9948030/48630198-0ac54e80-e992-11e8-8f6f-b7795b99ea16.png)

In 3.0, they're left-aligned:

![Two Scratch cats with speech bubbles containing left-aligned text; one saying "A.", the other "Hey now, you're an all-star, get your game on, go play"](https://user-images.githubusercontent.com/9948030/48630241-26c8f000-e992-11e8-8a43-df5735d5a7fb.png)

Bonus - in 1.4, they're center-aligned, just like 2.0 but not 3.0:

![Two Scratch cats with speech bubbles containing center-aligned text; one saying "A.", the other "You're a wizard, Harry!"](https://user-images.githubusercontent.com/9948030/48630276-4233fb00-e992-11e8-91e9-df6a5f9c0ccd.png)

I'm curious why this change was made. Is it an intentional design decision? (If so, why?) Or is it just that there hasn't been any code written to center-align speech bubble text yet?

**Comment by thisandagain** [comment]
@towerofnix Good question! It was something we did to make the text in bubbles a little easier to read. http://uxmovement.com/content/why-you-should-never-center-align-paragraph-text/
