### ISSUE TITLE
Fence width logic differs between Scratch 2 and Scratch 3

### ISSUE THREAD

**Issue by ktbee** [LLK/scratch-render#396]
### Expected Behavior

The fence width and height should be the same for Scratch 2 and 3

### Actual Behavior

`getFencedPositionOfDrawable` in RenderWebGL.js sets an inset for [width](https://github.com/LLK/scratch-render/blob/develop/src/RenderWebGL.js#L1305) and [height](https://github.com/LLK/scratch-render/blob/develop/src/RenderWebGL.js#L1311) instead of one inset for both like [Scratch 2 uses.](https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchSprite.as#L209)

### Steps to Reproduce

Set a sprite that is taller than it is wide to go off the edge of the stage. You'll observe that it goes further off the stage in Scratch 2 than 3.

Example Scratch 3 project: https://scratch.mit.edu/projects/278625596

![screen shot 2019-01-10 at 1 37 27 pm](https://user-images.githubusercontent.com/7991694/50989280-ee024e80-14dc-11e9-99a7-d64e83acbc9f.png)

Original sb2 for that project

[inset-test.sb2.zip](https://github.com/LLK/scratch-render/files/2746638/inset-test.sb2.zip)

![screen shot 2019-01-10 at 1 38 19 pm](https://user-images.githubusercontent.com/7991694/50989322-05413c00-14dd-11e9-9d1b-060bc0cf6cdb.png)

[This could be related to why you don't fall into pits!](https://github.com/LLK/scratch-vm/issues/1451)

**Comment by thisandagain** [comment]
Very likely the root cause of https://github.com/LLK/scratch-vm/issues/1451

**Comment by ktbee** [comment]
Resolved by https://github.com/LLK/scratch-render/pull/400
