### ISSUE TITLE
Off-stage stamping disables pen

### ISSUE THREAD

**Issue by helderman** [LLK/scratch-render#425]
### Expected Behavior

Using 'pen' blocks, it is possible to make smooth animations. A single sprite could draw every frame in the animation using a combination of pen strokes and stamps of costumes. By design, a sprite cannot leave the stage completely; a 30 pixel wide section of the sprite will remain visible. This is a problem when you want a stamped image to smoothly slide on or off the stage. A common workaround is to switch between costumes; a big costume to move the sprite, a smaller costume to be stamped. In practice, this means I regularly do an 'off-stage' stamp (i.e. the sprite's current costume is outside the boundaries of the stage). In Scratch 2.0, this has never been a problem.

### Actual Behavior

In Scratch 3.0, an 'off-stage' stamp may make the sprite's pen ineffective. You can do 'pen down' and move the sprite wherever you like, but there will be no more visible pen strokes. This happens under the following conditions:

- Before stamping, the sprite has made a visible pen stroke. (Thanks to Scratcher 'DadOfMrLog' for pointing this out.)
- When stamping, the sprite was located so far to the right or so far to the top that its current costume was outside the boundaries of the stage.

Please note that the pen can be brought back to normal operation by doing an 'on-stage' stamp. This is also the only known workaround: always have an off-stage stamp followed by an on-stage stamp (any costume will do, even an empty one); then pen operations will be effective again.

### Steps to Reproduce

Make a project with a single invisible sprite with 2 costume (one big, one small) and a script that takes the following steps:

- Change to big costume
- Move to center of stage
- Make a pen stroke (i.e. pen down, move, pen up)
- Move as far to the right or top as possible
- Change to small costume
- Stamp
- Move back to center of stage
- Make a pen stroke (i.e. pen down, move, pen up)

Notice how the final step has no visible effect - NOT OK.

I shared a Scratch project to demonstrate the problem:
https://scratch.mit.edu/projects/276965631/

### Operating System and Browser

Reproducible on Windows 10, both with Google Chrome 32-bit (version 73) and Firefox 64-bit (version 65).

**Comment by thisandagain** [comment]
@BryceLTaylor Can you repro?

**Comment by BryceLTaylor** [comment]
I sure can.  It's strange that you don't see this behavior if the sprite is off to the left or the bottom when it stamps.  You only see it if you stamp above or to the right.  It calls to mind the fencing issues which were similarly asymmetrical.

I've made this project to repro: https://scratch.mit.edu/projects/297069081/editor

The step of drawing a line on the stage seems extraneous at first, but without it you don't see the issue.  

It also seems that you only need the sprite to be big in order to ensure that you stamp the small sprite off of the stage.  it doesn't matter if you draw the lines with the sprite large or small.  It is easier to see the lines if you draw them with the small sprite.

**Comment by BryceLTaylor** [comment]
It seems to be preventing lines from being drawn until it gets to the end of the stack.  If it runs again, it will be able to draw lines again.  If you put a number of the `draw line` call blocks at the bottom of the stack it will not draw lines for any of them.  However, if you put the `draw line` call block in a forever loop at the end of the stack it will draw lines forever.  Presumably it fails to draw a line the first time and will successfully draw lines forever after that.

![DrawLineAfterStamping](https://user-images.githubusercontent.com/1088291/54947834-a43cd800-4f11-11e9-9c07-d9b689f63c67.png)
