### ISSUE TITLE
Sprites zoomed with "dot" trick become blurry

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-render#428]
### Expected Behavior

Sprites are never blurry.

### Actual Behavior

Zooming a sprite with the "dot" trick (see below) can make it end up being blurry:

![The Scratch Cat sprite zoomed in dramatically, so you can only really see the colors of it filling up the screen; the edges around the shapes are pixelated.](https://user-images.githubusercontent.com/9948030/54936916-405ee300-4f02-11e9-8396-de52e0e2d844.png)

![A nondescript scene demonstrating more blur. There's another sprite which is not blurry on top of the blurry scene, to compare.](https://user-images.githubusercontent.com/9948030/54937135-9af83f00-4f02-11e9-8f29-69ece53486dc.png)

### Steps to Reproduce

There is a trick for zooming sprites/costumes to values larger than they would typically zoom to, called the "dot" trick for discussion here:

!["switch costume to (dot); set size to 12400%; switch costume to (costume1)"](https://user-images.githubusercontent.com/9948030/54936811-04c41900-4f02-11e9-8646-5c93e70889ec.png)

A good demo of this bug in effect is [Mega Zoom Trick](https://scratch.mit.edu/projects/12623360/) by griffpatch, but this happens pretty much anywhere you use this trick to zoom the sprite past the normally-allowed values (which is necessary to build large, scrolling scenes).

### Operating System and Browser

Firefox 67.0b4, Linux (Debian).

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/4211
