### ISSUE TITLE
Low quality on vector costumes in smaller stage mode

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-render#437]
### Expected Behavior

Lines and curves look crisp or smooth regardless of stage scale. In particular they should not have "jaggies" or uneven/missing pixels at any scale.

### Actual Behavior

When using the smaller stage mode, vector costumes often end up looking bad. From #431:

| Full size stage      | Smaller stage |
| -----------            | ----------- |
| ![Screen Shot 2019-04-01 at 2 17 11 PM](https://user-images.githubusercontent.com/7991694/55350065-318ba980-5489-11e9-8cf8-ce7567154d1c.png)     | ![Screen Shot 2019-04-01 at 2 17 23 PM](https://user-images.githubusercontent.com/7991694/55350080-3ea89880-5489-11e9-89a9-d4d04e2dc2a3.png) |

### Steps to Reproduce

1. Load a vector costume such as the default Scratch Cat.
2. Press the stage size button to switch to a smaller stage.

Scaling the sprite up or down using `set size to _` or `change size by _`, or entering and leaving full-screen "presentation" mode, may affect the results as well.

**Comment by mzgoddard** [comment]
I poked around. It seems that the gui is passing the small scale down to render correctly. The small size is 0.85. This makes the rendered canvas 408 x 306.

I think ... the quality issue demonstrated in the above images isn't a macro scaling issue but a micro scaling issue. Any scale that isn't the scale of the texture drawn to screen with **fine** line detail will present this quality issue at some scale other than the one drawn.

We can't fix it by drawing at a close higher or lower scale and downsampling or upsampling (mipmaps). It will cause the line to have the wrong stroke width as it tries to reduce or produce pixels that are in the higher scaled or lower scaled image.

At a finer scale, the small difference from 1x to 0.85x presents not really stroke width issues, but small areas where information is missing when the svg lines were aliased, making these kind of depressions.

At the moment I can think of a few solutions.

1. Render every requested scale. When drawn the svg is rendered into pixels we lose the line information. We can't reproduce the svg information with texture filtering, but a more comprehensive analysis of the region of an image that we probably can't do in webgl.
2. Draw the SVG as a mesh. We wouldn't lose the line information but would need to add tech to produce that mesh, and figure out how to support touching block operations.
3. Create a kind of edge/normal map texture to provide a bias when filtering. Maybe look up techniques for drawing smooth shadows with texture maps.

I'm not sure about these solutions hopefully there is something else we can do.

**Comment by mzgoddard** [comment]
4. Maybe we need GPU mip sampling with CPU mip generation and handle edge clamping and skin scaling in the fragment shader. (Not sure if this would solve it though.)

**Comment by adroitwhiz** [comment]
This looks like the same root issue as #334, which is that ```Drawable.useNearest()``` doesn't operate in screen space as it should. Essentially, it takes into account the sprite's scale but not the _stage's_ scale, and as a result the skin uses nearest-neighbor interpolation which causes jaggies. If the skin uses linear interpolation, it looks a bit blurry but definitely passable:

![image](https://user-images.githubusercontent.com/25993062/56457287-4ea7ef80-6346-11e9-80c3-c44ba58718cf.png)
