### ISSUE TITLE
Should Skin.getFenceBounds ever call getFastBounds?

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#446]
### Expected Behavior

```Skin.getFenceBounds()``` is used to determine how far a drawable can move off-stage, and so it should return a consistent value.

### Actual Behavior

```Skin.getFenceBounds()``` calls ```drawable.getFastBounds()```, which returns different values depending on whether the drawable's convex hull exists. While this behavior is overridden in ```BitmapSkin```, ```SVGSkin``` retains it.

I'm not sure whether this could ever become a practical problem. Is it supposed to happen/okay?

**Comment by griffpatch** [comment]
Could this explain https://github.com/LLK/scratch-vm/issues/2076 or
https://github.com/LLK/scratch-vm/issues/2078
