### ISSUE TITLE
PenSkin still has a canvas, which it never uses

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#450]
### Expected Behavior

The `PenSkin` class, which is now implemented in WebGL, should not create an instance of a `<canvas>` element.

### Actual Behavior

It does, and this `<canvas>` element, despite never being drawn to, is somewhat intertwined into the `PenSkin`'s code.

**Comment by adroitwhiz** [comment]
@cwillisf i think i'm supposed to discuss this?

**Comment by thisandagain** [comment]
@cwillisf Any thoughts on this? Would you be open to a PR that remove this `canvas` element?
