### ISSUE TITLE
RenderWebGLLocal is not a constructor

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-render#457]
{% load staticfiles %}
<!DOCTYPE html>
<html lang="'en'" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Scratch 3.0</title>
    </head>
    <body>
        <canvas id="myStage"></canvas>
        <canvas id="myDebug"></canvas>

        <script src="{% static 'scratch3.0/scratch-render/dist/web/scratch-render.min.js' %}"></script>
        <script>
            var canvas = document.getElementById('myStage');
            var debug = document.getElementById('myDebug');

            var renderer = new window.RenderWebGLLocal();
            renderer.setDebugCanvas(debug);
            function drawStep() {
                renderer.draw();
                requestAnimationFrame(drawStep);
            }
            drawStep();

            var worker = new Worker('worker.js');
            renderer.connectWorker(worker);
        </script>
    </body>
</html>

Error: TypeError: window.RenderWebGLLocal is not a constructor

**Comment by towerofnix** [comment]
RenderWebGLLocal was removed a long while ago (see #35). The developers just forgot to update the readme. I'm guessing you have to use just `new window.RenderWebGL()` now.

**Comment by Tsepu** [comment]
It is same:

TypeError: window.RenderWebGL is not a constructor

**Comment by towerofnix** [comment]
I'm not sure if dist builds are even supported in a straightforward-use way anymore at all. You may have to use [webpack](https://webpack.js.org/) with your own project to build a full dist file which `require()`'s `scratch-render`, as in [playground.js](https://github.com/LLK/scratch-render/blob/develop/src/playground/playground.js) (just substitute `require('../RenderWebGL')` with `require('scratch-render')`).

That said, I may be missing something obvious. It *may* be possible to use scratch-render without webpack; but I don't know if that is the case or not. Probably an ST developer will see this thread and have some advice soon.
