### ISSUE TITLE
Figure out why pen dots aren't/weren't round

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-render#465]
#423 introduced a workaround for oval-shaped pen dots. While pen dots look much better due to that change, the values used in the change were determined experimentally. I would prefer to know for sure 1) why the pen dots weren't already round, and 2) what exact values we should use, or if there's some other way we should be adjusting the pen drawing code to result in round dots. I strongly suspect that figuring out the former will lead to figuring out the latter. I suspect this all has something to do with the stage aspect ratio but I have not yet investigated.

#438 may also be interesting for this investigation.

**Comment by adroitwhiz** [comment]
I think #580 fixes this
