### ISSUE TITLE
getConvexHullPointsForDrawable is hard to understand

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#473]
Currently, the `RenderWebGL._getConvexHullPointsForDrawable()` function's algorithm is hard to understand. What little documentation there is amounts to an extremely literal description of what the code does, and the variable names are very obfuscated. Ideally, the convex hull algorithm would be clearly described and commented, with descriptive variable names.

**Comment by adroitwhiz** [comment]
@cwillisf I saw in your review of the PR adding this function that you were interested in better documentation for it. Would you be open to a PR that improves its ergonomics?

**Comment by cwillisf** [comment]
Certainly - that sounds great!

In general my stance on documentation is that I'm in favor of anything that makes maintaining the code easier. Adding documentation to help understand some tricky code can definitely help with maintenance by reducing the amount of time it takes to adjust code and/or reducing the chance of making mistakes when doing so. On the other hand, if we have pages of documentation for every little thing then the maintenance burden of the documentation itself can outweigh the benefit.

**Comment by linushp** [comment]
the getConvexHullPointsForDrawable is not indeed .
why not get  ConvexHullPoints from the skin  ??

**Comment by adroitwhiz** [comment]
> the getConvexHullPointsForDrawable is not indeed .
> why not get ConvexHullPoints from the skin ??

The convex hull is affected by effects like whirl, pixelate, and fisheye, which are unique to each drawable.
