### ISSUE TITLE
"Touching color (white)" behaves inconsistently

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#488]
### Expected Behavior

"touching color (white)" should always return `true` over a white backdrop.

### Actual Behavior

On the CPU path, "touching color (white)" only returns true when the sprite calling it is within the bounds of another drawable. On the GPU path, it never returns true.

### Steps to Reproduce

See [this project](https://scratch.mit.edu/projects/322985073/).

**Comment by fsih** [comment]
I checked 2.0, and it looks like it... never says true for touching white?

![image](https://user-images.githubusercontent.com/2855464/68342354-65325000-00b8-11ea-8100-594bf03fe583.png)

Our behavior of sometimes saying true for touching white is definitely wrong, but I wonder if there are compatibility concerns for now saying true for touching white? @cwillisf @kchadha

**Comment by adroitwhiz** [comment]
Can you post the test project as a .zip? I created a simple test project in [s2online](https://s2online.github.io/), and it does return true there:
![image](https://user-images.githubusercontent.com/25993062/68342567-e25dc500-00b8-11ea-8bc8-50155a8f5b12.png)

**Comment by fsih** [comment]
My mistake, the script wasn't running :p

**Comment by adroitwhiz** [comment]
The plot thickens:
[transparent-background.sb2.zip](https://github.com/LLK/scratch-render/files/3816979/transparent-background.sb2.zip)

**Comment by fsih** [comment]
oh no

**Comment by fsih** [comment]
So in conclusion:
- Transparent background doesn't count as touching white in Scratch 3 or Scratch 2
- Except transparent in the bounding box of another color in the background does count as white in Scratch 3 but not Scratch 2
- And sprites touching past the edges of the stage count as touching white in Scratch 2 but not Scratch 3

**Comment by fsih** [comment]
Talked to @cwillisf and we decided that we want to keep the scratch 2 behavior, except that when touching outside of the stage, touching white should not be true. That is
* Transparent background doesn't count as touching white in Scratch 3 or Scratch 2
* White background should count as touching white

**Comment by adroitwhiz** [comment]
I tried matching that behavior when you first showed what 2.0 did, but got stuck on the case of gradients which fade to transparent:

(this is a .sb2)
[transparent gradient backdrop.zip](https://github.com/LLK/scratch-render/files/3866073/transparent.gradient.backdrop.zip)

There's a specific point along the gradient where 2.0 decides it's no longer touching grey, but I have no idea why, because it appears the 2.0 "touching color" code completely ignores alpha.

Perhaps you or @cwillisf might be able to shed some light on how the Flash BitmapData class behaves.

Adobe [says it's premultiplied](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html#getPixel()), but if that's the case, there should be erroneous "touching color" results from rounding errors when un-premultiplying the colors, which I don't see.

The [BitmapData.threshold function is used to test color values](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/scratch/ScratchStage.as#L655), but it looks like the [mask is set to completely ignore alpha values](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/scratch/ScratchStage.as#L643).

The "color () is touching color()" block [*does* mask out the alpha value by `0xF0` instead of ignoring it entirely](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/primitives/SensingPrims.as#L186), but that doesn't explain why the "*sprite* is touching color ()" block behaves like it does.

**Comment by fsih** [comment]
The gradient background touching color issue feels like a very specific edge case, and we don't have examples of 2.0 projects that depend on the behavior that we've seen yet. Given that, I think for 3.0 we can move ahead with anything that feels right. I think it would be fine to have touching gray be true throughout the gradient. Thoughts?

**Comment by adroitwhiz** [comment]
Unfortunately, that won't work because while `getImageData` doesn't return premultiplied values, it *does* return values that were stored premultiplied and then divided by alpha, resulting in a severe loss of precision as transparency increases. Near the gradient's transparent end, it would take on increasingly divergent shades of grey.

**Comment by adroitwhiz** [comment]
@cwillisf @fsih 

Mystery solved! Scratch 2.0 doesn't count transparent backgrounds as "white" because, as can be seen [in this line](https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchStage.as#L590), it instead counts them as *this* color (`0xF0F080`):
![image](https://user-images.githubusercontent.com/25993062/73816046-9f91b300-47b5-11ea-9c4b-52ff603a0866.png)

You can test this for yourself with [this test project](https://github.com/LLK/scratch-render/files/4157747/magic-color.zip) (rename extension to .sb2).

Is this worth emulating?

**Comment by adroitwhiz** [comment]
Also, since `colorMatches` only tests the top 5 bits (at most) of each color, it appears colors with an alpha of 248 or greater don't suffer from enough precision loss to affect the result.

You can test this with the following code:
```js
(() => {
let threshold = 256;
while (threshold > 0) {
    for (let i = 0; i < 256; i++) {
        let unrounded = Math.round(i * (threshold/256)) / (threshold/256);
        if (((Math.round(unrounded) ^ i) & 0b11111000) !== 0) return threshold + 1;
    }

  threshold--;
}
})()
```

This means that, if you don't want to emulate the weird yellow color behavior, "touching color" can instead consider colors with an alpha < 248 to be too transparent to test.

**Comment by fsih** [comment]
I'm dying inside

**Comment by fsih** [comment]
Since I don't think we should keep the ship-it-yellow behavior, let's decide that touching white should be true when touching the background color. I think that's the most reasonable thing for a beginner to expect, and anyone who is relying on the current behavior is probably really confused by what we're doing

**Comment by fsih** [comment]
Side note: we should search for how many projects are using touching color F0F080 in jupyter
