### ISSUE TITLE
Black and white dots appearing on stage on Chromebook

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#500]
Several users are reporting seeing black dots on stage.
I'm seeing this issue on Samsung Chromebook 3, Chrome version 76. Was NOT seeing it on Chrome version 75.
Not able to repro on Mac 10.14, Chrome 76
Not able to repro on Windows 10, Chrome 76

The issue is visible at all stage scales, whether in the editor or on the project page. The dots are not visible in the paint editor. The dots appear regardless of the color of the costume or whether the costume is bitmap or vector. Dots change location when the sprite is dragged to a different place on the stage.

![Screenshot 2019-08-21 at 11 46 18 AM](https://user-images.githubusercontent.com/2855464/63454862-a2703580-c419-11e9-8be8-26a5429c2183.png)
![Screenshot 2019-08-21 at 11 45 36 AM (1)](https://user-images.githubusercontent.com/2855464/63454864-a2703580-c419-11e9-924d-cd0e417c78e7.png)
![Screenshot 2019-08-21 at 11 45 59 AM](https://user-images.githubusercontent.com/2855464/63454859-a2703580-c419-11e9-9d82-7d7674f945ce.png)
![Screenshot 2019-08-21 at 11 50 48 AM](https://user-images.githubusercontent.com/2855464/63455368-a81a4b00-c41a-11e9-9b48-066416d36706.png)

**Comment by fsih** [comment]
A couple of user threads
https://scratch.mit.edu/discuss/topic/367470/
https://scratch.mit.edu/discuss/topic/367460/

**Comment by fsih** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=996323 on Chrome

**Comment by fsih** [comment]
Some comments from @paulkaplan 
a couple other observations: it isn’t in the paint editor, meaning it isn’t a 2d canvas problem. It also isn’t in the image you get when you drag the cat around on the stage, which is kinda wild because that is pixels retrieved from the renderer itself. It is present on the thumbnail (which makes sense, that is just the canvas converted to pixels)

**Comment by fsih** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=996323#c2 Chrome responded on the bug and wants a minimum repro. @cwillisf any chance there is a very stripped-down version of the renderer that I could start from?

**Comment by adroitwhiz** [comment]
Does the issue appear in the "playground"?

**Comment by paulkaplan** [comment]
@adroitwhiz it does, yeah

**Comment by fsih** [comment]
@BryceLTaylor this should be up on scratch.ly now. There shouldn't be random black dots on the stage on chromebooks
