### ISSUE TITLE
How to implement mouse click event? (was: 怎么实现鼠标点击事件？)

### ISSUE THREAD

**Issue by sxz1314** [LLK/scratch-render#504]
怎么实现鼠标点击事件？

**Comment by linushp** [comment]
参考 scratch-gui项目

**Comment by sxz1314** [comment]
canvas.addEventListener('mouseup', e => {
            const rect = canvas.getBoundingClientRect();
            const data = {
                isDown: false,
                x: e.clientX - rect.left,
                y: e.clientY - rect.top,
                canvasWidth: canvas.width,
                canvasHeight: canvas.height
            };
            console.log(data);
            mockMouse(data);
            e.preventDefault();
           // vm.postIOData('mouse', data);
           
        });
手机模式虽然执行这个方法了但是舞台没有效果，电脑上可以

**Comment by sxz1314** [comment]
> 参考scratch-gui项目
  canvas.addEventListener('mousedown', e => {
        const rect = canvas.getBoundingClientRect();
        const data = {
            isDown: true,
            x: e.clientX - rect.left,
            y: e.clientY - rect.top,
            canvasWidth: canvas.width,
            canvasHeight: canvas.height
        };
        console.log(data);
        vm.postIOData('mouse', data);
        e.preventDefault();
      
        
    });
  
    canvas.addEventListener('mouseup', e => {
        const rect = canvas.getBoundingClientRect();
        const data = {
            isDown: false,
            x: e.clientX - rect.left,
            y: e.clientY - rect.top,
            canvasWidth: canvas.width,
            canvasHeight: canvas.height
        };
        console.log(data);
        vm.postIOData('mouse', data);
        e.preventDefault();
    
       
    });
手机模式虽然执行这个方法了但是舞台没有效果，上电脑可以
您要是网求方便留一下联系方式吧我微信sxz13145

**Comment by cwillisf** [comment]
Mouse events in Scratch 3.0 are implemented in `scratch-gui`, as @linushp indicated. I would recommend taking a look at the `handleDoubleClick` function in `scratch-gui/src/containers/stage.jsx` for reference.

If you're using `scratch-render` without using `scratch-gui`, I recommend looking at the `'click'` event listener in `scratch-render/src/playground/playground.js`.
