### ISSUE TITLE
SVG backdrop centering

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#52]
SVG backdrops are not in the right position after applying rotation center for some reason. Those seem to almost always be off by a few pixels in both X and Y...it looks stage centers are a special case in 2.0: https://github.com/LLK/scratch-flash/blob/master/src/scratch/ScratchObj.as#L219

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
