### ISSUE TITLE
Vector sprites appear jagged after exiting full-screen mode

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#526]
### Expected Behavior

Vector sprites should never appear jagged.

### Actual Behavior

Vector sprites appear jagged if you enter full-screen mode then exit it:

Before full-screen | After full-screen
-- | --
![image](https://user-images.githubusercontent.com/25993062/69371549-0e0eac80-0c6e-11ea-8012-281ba2cc0e68.png) | ![image](https://user-images.githubusercontent.com/25993062/69371585-1ff04f80-0c6e-11ea-97f9-99698b6fc105.png)

This is because of `Drawable.useNearest`. https://github.com/LLK/scratch-render/pull/480 changed `useNearest` to take stage scale into account, but there's one missing variable still: the skin's dimensions.

In normal-stage mode, `useNearest` enables nearest-neighbor sampling because the drawable's screen-space scale is 100%. It doesn't ensure that one screen-space pixel is roughly the same size as one skin-texture pixel, assuming it to always be true. Entering full-screen mode causes the SVG skin to re-rasterize at a higher resolution, breaking this assumption.

### Steps to Reproduce

1. Create a new project
2. Enter full-screen mode
3. Exit full-screen mode

**Comment by fsih** [comment]
We noticed this too and felt it should be ok until https://github.com/LLK/scratch-render/pull/431 goes in
