### ISSUE TITLE
How to make use of scratch-render

### ISSUE THREAD

**Issue by jyh129143** [LLK/scratch-render#532]
I have built the render successfully,and I got a HTML page like this:
![image](https://user-images.githubusercontent.com/29747808/71073824-0fbf8780-21bc-11ea-8dfe-43bd5b6489dc.png)
But if I want to add a sb3 file to this page and run it,what can be done?

**Comment by jyh129143** [comment]
And what's the function of this page?It seems nothing happened after I chose a sb3 file
![image](https://user-images.githubusercontent.com/29747808/71074293-f8cd6500-21bc-11ea-8755-d11912c00770.png)

**Comment by apple502j** [comment]
You should always use scratch-gui. scratch-render and scratch-vm are just a component of it, not to be meant as a stand-alone app.

**Comment by fsih** [comment]
That page is the "playground" for testing scratch-render. If you want to be able to read sb3 files you probably want to build LLK/scratch-gui as apple502j says.

**Comment by jyh129143** [comment]
Thanks for replying.I'm trying to run an sb3 file on a stand-alone web page.I got two files, namely player.js and lib.min.js by running the command 'npm run build' on scratch-gui.I can run sb3 files successfully on a web page with that two files imported.However,the file lib.min.js has a very big size(20MB).I think when I run the command 'npm run build',too many modules are packaged to this file,which may not be necessary for running an sb3 file.So, is there any way to simplify the lib.min.js file when we run 'npm run build' command.

**Comment by apple502j** [comment]
Not really (if i remember correctly) @jyh129143

**Comment by jyh129143** [comment]
what a pity!
