### ISSUE TITLE
Costume stops updating stage after being cleared (not yet on prod)

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#538]
This is on https://llk.github.io/scratch-gui/develop/ but not yet on prod.

From @carljbowman (abridged)
4 Go into the paint editor
6 Delete the cat and draw anything with the brush tool
The cat should delete and the new drawing should be
Instead, nothing appears

**Comment by fsih** [comment]
@BryceLTaylor this is a regression so probably a blocker!

**Comment by fsih** [comment]
We're patching at 2am! It's all very exciting

**Comment by adroitwhiz** [comment]
![update svg renderer_1_1](https://user-images.githubusercontent.com/25993062/72047930-9e8a6600-3289-11ea-923e-3924fd2d8fd1.gif)

**Comment by fsih** [comment]
argh that gif is terrifying o_o
