### ISSUE TITLE
The "touching mouse" block doesn't work with vector costumes which have never appeared

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#543]
### Expected Behavior

The "touching mouse" block should work with all sprites.

### Actual Behavior

The "touching mouse" block only works with vector costumes if they have previously been shown on screen.

### Steps to Reproduce

See [this project](https://scratch.mit.edu/projects/358459259/)

### Operating System and Browser

All

**Comment by BryceLTaylor** [comment]
That project does not indicate a bug.  The second sprite is hidden, so it will not interact with collisions.  Also, the block is "touching mouse-pointer" and not "touching sprite2"

**Comment by adroitwhiz** [comment]
I've deleted the other two sprites to make the problem clearer. When sprite1's costume is costume3, "touching mouse" should return true if the mouse is in the area covered by costume3. This doesn't happen if costume3 has never been rendered (in the demo project, the sprite switches back to costume4 before each frame is rendered).

**Comment by BryceLTaylor** [comment]
So touching sprites works fine, which implies a difference between touching sprite v. touching mouse pointer.  It could be when collisions are calculated, or how the data is stored about what to check.  Or something else.

**Comment by adroitwhiz** [comment]
It's because the "touching" data for a vector costume is never calculated until the costume's texture is fetched, which #544 fixes.
