### ISSUE TITLE
drawableScale should consider current render target

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-render#545]
### Expected Behavior

The scale of a Skin, including MIP choice for SVGSkin, should depend on the current render target. That is, the value returned by `_getDrawableScreenSpaceScale` should be different depending on whether we're drawing / going to draw to the query buffer or the buffer associated with the visible canvas. The method should probably be renamed along with this change, since it'll no longer always be associated with screen space.

### Actual Behavior

Currently the scaling factor is determined as if we're drawing to the buffer associated with the visible canvas, regardless of the actual current render target. This can lead to choosing a larger rasterization of an SVG skin than necessary, which could lead to minor artifacts in render queries.

I'm currently not aware of any project which works incorrectly due to this issue.

**Comment by adroitwhiz** [comment]
I don't see any WebGL API for getting the resolution of the currently bound framebuffer, and `twgl.FramebufferInfo` doesn't store the resolution either. Would it have to be manually specified, and if so, what's the best way to do so?
