### ISSUE TITLE
edited costume appears in slightly different position and causes jitter

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-render#547]
### Expected Behavior

If you duplicate a costume and then edit one part of it the rest of the costume should appear to be in the same place as the original costume.

### Actual Behavior

The second costume will draw in a slightly different place so that switching between the costumes quickly causes it to "jitter."  

![jitter](https://user-images.githubusercontent.com/1088291/72648375-e32c9600-3948-11ea-8193-ad2554d56fd1.gif)

Here is a project that shows this issue that came from the community: https://scratch.mit.edu/projects/359990077/

Note: sometimes the project won't appear jittery.  I looked at it and saw the jitter but @fsih could not see the jitter.  Going into fullscreen mode removed the jitter.  Returning to regular screen mode again did not put the jitter back.  

Tiny screen mode revealed the jitter every time.

This was reported originally in the forums here: https://scratch.mit.edu/discuss/topic/343787/

### Steps to Reproduce

Create a new project
Open the costume editor for the cat
Delete the second costume for the cat
Duplicate the first costume for the cat
Switch to the code tab
Create this stack:
![Screen Shot 2020-01-17 at 4 39 09 PM](https://user-images.githubusercontent.com/1088291/72648073-10c50f80-3948-11ea-8943-ff833b36abb8.png)
Run the code
Note: it looks like the cat is just sitting there on the stage
Return to the costume editor
Delete the cat's arm (on the right side of the sprite)
Note: the cat on the stage rapidly switches back and forth between a cat with and without the arm.  Also note that the whole cat bobs up and down.
Switch to full screen mode
Note: the jitter goes away (or is reduced)
Go back to regular screen mode
Note: the jitter is still gone (reduced)
Switch to small screen mode
Note: the jitter is back.

I see this much more severely when I am using an external monitor.  Moving it onto the laptop screen removed/reduced the jitter.

### Operating System and Browser

Mac 10.14.6 Chrome

**Comment by adroitwhiz** [comment]
This looks like a dupe of #427

**Comment by BryceLTaylor** [comment]
I copied my repro steps over to #427 .  Closing this issue as a duplicate.
