### ISSUE TITLE
Stamp Quality Differs Depending on Stage Size

### ISSUE THREAD

**Issue by RexScratch** [LLK/scratch-render#558]
### Expected Behavior

Stamp quality should not noticeably differ based on the resolution or size of the stage (such that using full screen mode increases the stage size/resolution).

### Actual Behavior

Stamp quality appears to significantly improve in full screen mode compared to normal screen and small screen mode.

### Steps to Reproduce

Go to https://llk.github.io/scratch-gui/develop/#377548941. Pressing 1 will draw on the left side, 2 in the middle, and 3 on the right side. Pressing s will change the text size. Clicking the green flag will erase everything. To see the issue, press 1 while in small screen mode in the editor, press 2 while in normal screen mode, and press 3 while in full screen mode. The differences should be obvious while in full screen mode, but still can be seen even in small screen mode with a 1920x1080 monitor.

This is the result on my system when in fullscreen:
![stamp bug](https://user-images.githubusercontent.com/47719663/76998613-68b9cb80-6923-11ea-99e9-eebac22d5fa0.png)

Note that this issue occurs even when not using rotation. Text is also not required, since the costumes are SVG paths rather than text.

Old project: https://llk.github.io/scratch-gui/develop/#371843546

### Operating System and Browser

Windows 10 Home 1903
Chrome 80.0.3987.122
1920x1080 resolution with 100% scaling

**Comment by adroitwhiz** [comment]
This looks like an unfortunate consequence of vector costumes' mipmaps being allowed to go up to [150% their original scale](https://github.com/LLK/scratch-render/blob/develop/src/SVGSkin.js#L130). This also appears in "smallish stage mode" for the default Scratch cat (see [this Bugs and Glitches post](https://scratch.mit.edu/discuss/topic/384061/).

To fix this, the mipmap code could be changed to use a mipmap between 50% and 100% its original scale (so that one texture pixel is never "blown up" to more than one screen pixel), but that would result in larger textures. It's unclear how that would impact memory usage and performance, but since [SVG sprites were getting double-scaled on high-DPI devices for a good chunk of time](https://github.com/LLK/scratch-svg-renderer/pull/84), it shouldn't be prohibitively expensive and may be well worth the quality boost.

**Comment by RexScratch** [comment]
> This looks like an unfortunate consequence of vector costumes' mipmaps being allowed to go up to [150% their original scale](https://github.com/LLK/scratch-render/blob/develop/src/SVGSkin.js#L130). This also appears in "smallish stage mode" for the default Scratch cat (see [this Bugs and Glitches post](https://scratch.mit.edu/discuss/topic/384061/)).
> 
> To fix this, the mipmap code could be changed to use a mipmap between 50% and 100% its original scale (so that one texture pixel is never "blown up" to more than one screen pixel), but that would result in larger textures. It's unclear how that would impact memory usage and performance, but since [SVG sprites were getting double-scaled on high-DPI devices for a good chunk of time](https://github.com/LLK/scratch-svg-renderer/pull/84), it shouldn't be prohibitively expensive and may be well worth the quality boost.

I don't know much about 3D graphics or mipmaps, so excuse me if I'm talking nonsense, but while I do see how that could result in lower quality, I don't see why that _should_ cause a difference in fullscreen mode. Since the resolution of the pen canvas is constant, why would the scale of the mipmap used when stamping differ based on the Stage resolution, which is completely irrelevant when stamping?

**Comment by adroitwhiz** [comment]
> Since the resolution of the pen canvas is constant, why would the scale of the mipmap used when stamping differ based on the Stage resolution, which is completely irrelevant when stamping?
This is another bug. Currently, stamping follows the same code path as normal stage drawing, so sprites' scales are incorrectly multiplied by the stage size.

**Comment by BryceLTaylor** [comment]
It's easy to see that stamping in small screen mode leads to a serious reduction in quality, but it's hard to see what you mean about full screen mode stamps. 

![Screen Shot 2020-03-04 at 5 05 30 PM](https://user-images.githubusercontent.com/1088291/75927493-77d84e00-5e3a-11ea-968f-e0b3eb8d1b4d.png)

@RexScratch @adroitwhiz Is there a particular sprite or quality of sprite that shows off the full screen improvement?  Can you include a screenshot like the one above that shows the difference between regular screen mode and full screen mode?

**Comment by adroitwhiz** [comment]
@BryceLTaylor https://scratch.mit.edu/projects/373572141/

This occurs when an SVG costume almost meets the threshold to reach a higher-resolution mipmap but doesn't make it.

In such a case, one texture pixel is blown up to 1.5 screen pixels, causing blurriness.

**Comment by adroitwhiz** [comment]
Also, did the project that @RexScratch provided not repro for you?

Here's what it looks like in normal stage mode:
![image](https://user-images.githubusercontent.com/25993062/75928635-d4d50380-5e3c-11ea-9d61-d100ef00e37d.png)

and in full-screen mode:
![image](https://user-images.githubusercontent.com/25993062/75928650-db637b00-5e3c-11ea-88b0-de2c1409795f.png)

This is on a 1920x1080 screen, but depending on the size of the browser UI, the taskbar, etc. the actual stage size in full-screen mode may vary.

**Comment by BryceLTaylor** [comment]
That project makes it very difficult to see both resolutions of the exact same thing at the same time or back to back so it's hard to compare differences in quality.  

There is also some important information missing from the report.  Specifically that it requires a rotation of the sprite and that it is at least more visible with text.  That is why I was asking for more information, since I needed to meet those conditions in order to see it.

**Comment by BryceLTaylor** [comment]
Here you can see some of the differences more clearly after I have rotated the cat:

![Screen Shot 2020-03-05 at 12 02 31 PM](https://user-images.githubusercontent.com/1088291/76005702-67c37b80-5ed9-11ea-9c87-35c58f0501ce.png)

**Comment by adroitwhiz** [comment]
Technically I don't think it needs to be rotated but it makes the problem much more visible

**Comment by RexScratch** [comment]
> That project makes it very difficult to see both resolutions of the exact same thing at the same time or back to back so it's hard to compare differences in quality.
> 
> There is also some important information missing from the report. Specifically that it requires a rotation of the sprite and that it is at least more visible with text. That is why I was asking for more information, since I needed to meet those conditions in order to see it.

I've added new information and a new project to (hopefully) better demonstrate this issue.
