### ISSUE TITLE
Emptied-out costumes retain their previous rotation centers

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#562]
### Expected Behavior

The rotation center of an empty costume should be (0, 0).

### Actual Behavior

When the contents of a costume are deleted in the paint editor, the now-empty costume's rotation center will still be set to whatever it was previously, only being set to (0, 0) upon a reload. This can cause fencing issues.

See [here](https://github.com/LLK/scratch-render/pull/559#issuecomment-595026465) for an instance of this.

### Steps to Reproduce

1. Open the paint editor
2. Delete the contents of the current costume
3. Observe how far the sprite is now fenced from the edges

### Operating System and Browser

N/A

**Comment by fsih** [comment]
While investigating this issue we found 2 related but different issues (running on a build with your fix patched)

The rotation center of a costume with width 0 but height non-zero should maybe not be 0,0
![width but not height 0 take 2](https://user-images.githubusercontent.com/2855464/77103769-56a65e80-69f1-11ea-84f5-65a01f45fd9d.gif)

When switching to a costume with width 0, the rotation center doesn't appear to get updated
![width but not height 0](https://user-images.githubusercontent.com/2855464/77103774-57d78b80-69f1-11ea-9ffc-bc5f0867aba8.gif)
