### ISSUE TITLE
Changing costume to one with zero width or height doesn't update correctly

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-render#571]
### Expected Behavior

When the user clicks a costume in the paint editor, the sprite's bounds should always be updated to match the costume.

### Actual Behavior

When the user clicks a costume in the paint editor, the sprite's bounds are updated to match the costume ONLY if the new costume's width and height are both non-zero.

### Steps to Reproduce

1. Create or edit a project which uses the pen extension
2. Make a sprite with at least two costumes:
   - One with a perfectly vertical or horizontal line, which due to #434 will get a 1x1 ImageData object internally.
   - One "normal" costume where width and height are both non-zero
3. Move the rotation center outside the costume for the "normal" costume
4. Activate the "normal" costume and use `pen down` and `go to random position` to see fencing behavior
5. While the project is running, switch to the other costume.

Expected: the sprite (Drawable) is fenced according to the new 1x1 ImageData
Actual: the sprite (Drawable) is fenced according to the previous "good" costume

The problem goes away after using the paint editor to adjust the rotation center of the zero-width / zero-height costume.

Example (thanks @fsih!)
![](https://user-images.githubusercontent.com/2855464/77103774-57d78b80-69f1-11ea-9ffc-bc5f0867aba8.gif)

**Comment by adroitwhiz** [comment]
I think this was fixed by https://github.com/LLK/scratch-vm/pull/2314.
