### ISSUE TITLE
"Touching" blocks on CPU path do not apply pixelate effect

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#573]
### Expected Behavior

"Touching" blocks should take effects into account.

### Actual Behavior

When using the CPU path for "touching" blocks (touching color, touching sprite, touching mouse), the pixelate effect is not taken into account, and as such there is a discrepancy between the pixels the sprite is supposed to cover and the pixels that count as being "touched".

For instance, see [this project](https://scratch.mit.edu/projects/378225265/), which stamps a 1x1 purple sprite whenever it touches the cat:
![image](https://user-images.githubusercontent.com/25993062/77215405-3e663a80-6aea-11ea-8362-d9eda651def9.png)

### Steps to Reproduce

1. Set a sprite's pixelate effect to a positive value
2. Try using a "touching" block in combination with that sprite
3. Notice a discrepancy between the sprite's appearance and the parts of the sprite that can be "touched"

### Operating System and Browser
All

**Comment by BryceLTaylor** [comment]
[Here's a project](https://scratch.mit.edu/projects/379155154/) that clearly shows the bug.

Note that if you put the mouse over the pixelated cat outside the original's outline it reports false and if you put the mouse inside the outline it reports true.
