### ISSUE TITLE
Pen dots in the lower right quadrant are not drawn on iOS Safari

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#589]
### Expected Behavior

Pen dots should always be drawn

### Actual Behavior

On iOS Safari, pen dots are not drawn in the lower right quadrant-- pen lines render fine:
![293F441E-3339-46D0-B4CD-191C97E4AD17](https://user-images.githubusercontent.com/25993062/80293417-32931700-872d-11ea-9f9e-d578703572fd.png)
(Screenshot taken from [this project](https://scratch.mit.edu/projects/388753987/))

### Steps to Reproduce

1. Create a project that draws pen dots all around the stage (with "pen down" immediately followed by "pen up")-- see [this project](https://scratch.mit.edu/projects/96967170/) as an example
2. Observe that on iOS Safari, the dots are not drawn in the lower right quadrant

### Operating System and Browser

iOS Safari

**Comment by BryceLTaylor** [comment]
I was able to reproduce a similar effect, except I was not able to produce pen dots anywhere on the entire stage on iOS Safari.  That is on an iPad mini 4 running iOS 12.4.1

@adroitwhiz when writing reproduction steps can you create a new project and describe the steps you take to produce the project that shows the issue?  That project is relatively complex and hard to see what parts are necessary to see the issue.

**Comment by apple502j** [comment]
@BryceLTaylor this should work as repro:
when gf clicked
forever
go to random position
pen down
pen up

**Comment by BryceLTaylor** [comment]
We received a help desk ticket (number 216463) that I think is about this issue.  Just putting this here so I can find it again later if necessary.
