### ISSUE TITLE
Pen lines over ~100 pixels long will not render on (some?) Android devices

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#595]
### Expected Behavior

All pen lines should show up.

### Actual Behavior

On (certain?) Android devices, lines over ~100 pixels long will not be drawn:
![image](https://user-images.githubusercontent.com/25993062/81107165-ba72e100-8ee4-11ea-8792-114d63562df0.png)

### Steps to Reproduce

1. Create a project
2. Add the pen extension
3. Click "pen down"
4. Make the active sprite move >100ish steps
5. Observe that only a pen dot is drawn, whereas both a pen dot and a pen line should be drawn

I've also created [a repro project that tests lines of different lengths](https://scratch.mit.edu/projects/392244913/).

### Operating System and Browser

Android, Chrome + Firefox + others?

Tested on a OnePlus 6T with an Adreno 630 GPU-- the specific model of GPU may play a role in this as well.

**Comment by adroitwhiz** [comment]
This is still appearing on certain Android devices to a lesser degree

**Comment by apple502j** [comment]
repro on forum by Chromebook user: https://scratch.mit.edu/discuss/post/3992783/

**Comment by BryceLTaylor** [comment]
@apple502j That forum post shows an issue that seems to have been fixed by the deploy last week.  I think they were seeing a different issue.  The problem shown by this issue was definitely NOT fixed by last week's deploy, though.
