### ISSUE TITLE
Pen support

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#6]
Thoughts:
- Provide a method to draw a line from (x1, y1) to (x2, y2) at color (RGB), width (px). VM handles color calculations and deciding when to draw lines.
- Stamp method for current drawable and clear method also provided.

I believe scratch-flash's pen draws the equivalent of canvas `lineCap`="round". In doing the HTML5 player, I also remember something about drawing lines at .5px off to prevent blur, but there might be a better way to deal with that.

**Comment by BookOwl** [comment]
Don't forget that the Scratch pen supports alpha.

**Comment by thisandagain** [comment]
Notes from meeting with @cwillisf 

#### Approach
- `Pen` is a `Drawable` with a specific type of skin which provides drawing methods
- `Pen` includes three public methods
    - `draw` (x1, y1, x2, y2, width, rgba)
    - `clear`
    - `stamp` (x, y, drawable_id)
- Set pen layer to be the render target and render quads directly

#### Problems
- Getting the lines to look correct
    - Render a quad 
    - Write a shader
    - `discard` around the radius to get "round" line caps
- Can you write on top of the existings buffer
    - Draw the current pen layer otherwise we'll need to "double buffer" (write self, write line, to pen layer)

#### Questions
- How are we thinking about HDPI screens?
    - Resolution of the display
    - Resolution of the query layer (touching color)

**Comment by liam4** [comment]
Might be worth throwing out that you could be able to stamp pen data!

(`Pen instanceof Drawable`; `aPen.stamp(aDrawable)`; `aPen.stamp(aPen)`)

**Comment by tmickel** [comment]
@thisandagain @cwillisf 

Can you explain a little more about why drawing lines this way vs. using Canvas 2D's existing line drawing methods? I was imagining that Canvas 2D would give us the same exact lines as Scratch 2.0, and we wouldn't have to deal with a line-cap shader or antialiasing since that would be handled by canvas/Skia/etc.

**Comment by cwillisf** [comment]
Hmm... that could be worth investigating for lines, though I think stamp would become more difficult in that situation. Still, getting good pen edges and line caps in exchange for more stamping work might be a good trade.

Part of the reason I hadn't considered it at first is because I assumed this wasn't possible to do this, but here's at least one person claiming it works:
http://stackoverflow.com/questions/22570235/how-do-i-use-an-html5-canvas-as-a-webgl-texture
I thought I had heard that it was forbidden in order to prevent browser fingerprinting and stuff like that.

**Comment by tmickel** [comment]
@thisandagain @cwillisf Sad to see this hit the backlog. If no one else has time for it, would it be ok if I took a try?

**Comment by dekrain** [comment]
Are you planning to do something similar to me?

**Comment by tmickel** [comment]
Hey @dekrain - Not sure! I hope we can follow something like the plan above.

**Comment by cwillisf** [comment]
I think I'm going to try to get something going for project and asset loading & storage. If nobody gets to pen until after I have a good start on that, this will probably be next on my list. @tmickel if you have time to look at this before I get to it then that's fine with me :)

**Comment by dekrain** [comment]
> Are you planning to do something similar to me?

Oh, sorry. I mean speech bubble.

**Comment by tmickel** [comment]
@cwillisf Sweet - I can try to do #54 instead.
