### ISSUE TITLE
Gradients sometimes not rendering correctly

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-render#61]
The "balloons" background is a good demo of this.

2.0 reference:
<img width="244" alt="screen shot 2016-11-14 at 12 34 00 pm" src="https://cloud.githubusercontent.com/assets/120403/20275487/bcf156f2-aa66-11e6-9dd1-8d812351c046.png">

scratch-render:
<img width="228" alt="screen shot 2016-11-14 at 12 34 08 pm" src="https://cloud.githubusercontent.com/assets/120403/20275491/c12a710e-aa66-11e6-91be-b75739584204.png">

Note that the balloons look fine in scratch-render, but the "floor" is a solid purple instead of a linear gradient.

**Comment by tmickel** [comment]
Something is definitely up with "top-to-bottom" linear gradients:

2.0 reference:
<img width="486" alt="screen shot 2016-11-14 at 12 38 26 pm" src="https://cloud.githubusercontent.com/assets/120403/20275627/5872e2c6-aa67-11e6-9da0-5d0283cfdbc3.png">

scratch-render:
<img width="522" alt="screen shot 2016-11-14 at 12 39 22 pm" src="https://cloud.githubusercontent.com/assets/120403/20275646/644abd58-aa67-11e6-9701-5176ab037201.png">

These were simple to make in the paint editor. In the balloons example, it looked like no gradient was being rendered; in this example, it looks like possibly a radial gradient is there instead of a linear one.

**Comment by tmickel** [comment]
Ok, here is my theory:

The linear gradient for the background above exported from Scratch looks like this:
>     <linearGradient id="grad_1" y2="1">
>       <stop offset="0" stop-color="#000000" stop-opacity="1"/>
>       <stop offset="1" stop-color="#FFFFFF" stop-opacity="1"/>
>     </linearGradient>

One way to get it to render correctly in browsers is also providing x1, x2, y1 properties like this:

>     <linearGradient id="grad_1" x1="0" x2="0" y1="0" y2="1">
>       <stop offset="0" stop-color="#000000" stop-opacity="1"/>
>       <stop offset="1" stop-color="#FFFFFF" stop-opacity="1"/>
>     </linearGradient>

I don't understand this because MDN says not providing these properties should be as if they are set to 0 anyway. But this doesn't appear true in practice...

**Comment by tmickel** [comment]
For the balloons, the gradient appears to be specifying its coordinates in something like _Scratch coordinates_:

`x1="393.7021" y1="-132.3242" x2="396.8778" y2="-41.3831" gradientUnits="userSpaceOnUse"`

But I don't think these are not actually SVG "user space" coordinates for the relevant object, since the viewBox is all positive. Not sure how to fix that, but hopefully it's just a simple transform...

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
