### ISSUE TITLE
Disable SVG Quirks on Non-Scratch SVGs

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-render#63]
### Correct:

![capture](https://cloud.githubusercontent.com/assets/17478432/20866619/2f89a7f8-b9ff-11e6-9660-755792c2bce8.PNG)

### In Scratch:
![capture2](https://cloud.githubusercontent.com/assets/17478432/20866622/49bf3962-b9ff-11e6-96aa-086b19b15d08.PNG)

### Browser:

MS Edge/Google Chrome (VM Still Doesn't Work on edge due to default toolbox)

### Download:

http://www.wpollock.com/SVG/sphere.svg

**Comment by tmickel** [comment]
Could you provide a link to the SVG or the Scratch 2.0 project?

**Comment by TheBrokenRail** [comment]
Here you go:

http://www.wpollock.com/SVG/sphere.svg

**Comment by tmickel** [comment]
Unfortunately Scratch 2.0 does a _very_ bad job of rendering this SVG:
<img width="193" alt="screen shot 2016-12-19 at 2 27 47 pm" src="https://cloud.githubusercontent.com/assets/120403/21326136/5d9b8a4a-c5f7-11e6-81f2-fdd174a3de5e.png">
For 3.0, though, it looks like the only thing wrong is the text positioning: I think the solution would be to render the SVG without the "2.0 quirks mode" transformations.

**Comment by TheBrokenRail** [comment]
Are you planning on adding a way to disable this? Like in a menu a Scratch 2.0 Mode for each costume?

**Comment by CosmicWebServices** [comment]
@TheBrokenRail that will be too confusing maybe there can be a way for scratch-vm to find a problem with the svg...

**Comment by TheBrokenRail** [comment]
No, I think it will be necessary as the renderer cannot tell the difference if it is a scratch svg or not.

**Comment by TheBrokenRail** [comment]
Changed Issue to be more constructive (now has download link)

**Comment by TheBrokenRail** [comment]
![2 0](https://cloud.githubusercontent.com/assets/17478432/22183599/de35cb36-e08f-11e6-949a-9e1f2a231ef1.PNG)
Here's a more subtle example this time with a scratch svg.
Links:
https://llk.github.io/scratch-vm/#67575180
https://scratch.mit.edu/projects/67575180/
Screenshot:
3.0:
![3 0](https://cloud.githubusercontent.com/assets/17478432/22183595/c9cd6ad2-e08f-11e6-94af-66c46f10af3e.PNG)
2.0:
![2 0](https://cloud.githubusercontent.com/assets/17478432/22183605/e4fa76ec-e08f-11e6-8040-66c71c44b4cd.PNG)

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/519
