### ISSUE TITLE
Some pen strokes result in large, blurred circles on iPhone Safari

### ISSUE THREAD

**Issue by RexScratch** [LLK/scratch-render#642]
### Expected Behavior

Pen strokes should not result in large, blurred circles.

Example:
![IMG_0032](https://user-images.githubusercontent.com/47719663/84619862-fca42080-ae9b-11ea-85a7-ea0d627b6da1.jpeg)

### Actual Behavior

Pen strokes often result in large, blurred circles.

Example:
![IMG_1562](https://user-images.githubusercontent.com/47719663/84619926-2a896500-ae9c-11ea-97e1-99c386932d1f.jpeg)

### Steps to Reproduce

On an iPhone, run one of the following projects on the project page:
- https://scratch.mit.edu/projects/278999727/
- https://scratch.mit.edu/projects/276932192/
- https://scratch.mit.edu/projects/318234147/
- https://scratch.mit.edu/projects/262564340/
- https://scratch.mit.edu/projects/236128688/

This doesn’t seem to be an issue limited to a few specific projects; most projects using the pen should produce this issue.

### Operating System and Browser

iPhone XS iOS 13.5.1 Safari

Cannot reproduce on a 2019 iPad on iOS 13.5.1

**Comment by apple502j** [comment]
KimiruHamiru said it happens when the pen is down while the sprite x or y is not integer: see https://scratch.mit.edu/discuss/post/4123687/
repro project: https://scratch.mit.edu/projects/404686504/
on iPad: 
![image](https://user-images.githubusercontent.com/33279053/84620466-087ef980-af13-11ea-921a-9384f8e3dfcf.png)

**Comment by RexScratch** [comment]
> KimiruHamiru said it happens when the pen is down while the sprite x or y is not integer: see https://scratch.mit.edu/discuss/post/4123687/
> repro project: https://scratch.mit.edu/projects/404686504/
> on iPad:
> ![image](https://user-images.githubusercontent.com/33279053/84620466-087ef980-af13-11ea-921a-9384f8e3dfcf.png)

(Using Google Translate)

They mentioned using a iPad Mini 5, which is interesting because I couldn’t reproduce this issue on a 2019 iPad. The iPhone XS and iPad Mini 5 both have the A12 Bionic SoC, whereas the 2019 iPad has the A10 Fusion SoC.

**Comment by RexScratch** [comment]
It does seem that precision plays a role, since not all non-integer coordinates cause this issue:
https://llk.github.io/scratch-gui/develop/#404937682

When the x-coordinate is offset by -0.25 or -0.5, the issue doesn’t occur. However, when the x-coordinate is offset by -0.1, the issue does occur.

**Comment by fsih** [comment]
It's also reproing on iPhone 8, but not on iPad mini 4

**Comment by MineUp1000** [comment]
K, I noticed this glitch occurred recently and made a forum about it, but thankfully I was given <a href="https://github.com/LLK/scratch-render/issues/642/">this link</a>!!!
(Thanks @apple502j). I think that this glitch occurred at the same time the <a href="https://scratch.mit.edu/discuss/topic/414997/">Fullscreen Glitch</a> Occurred 

### **EDIT**

This <a href="https://llk.github.io/scratch-gui/develop/#411430200">link</a>, which I created myself is a test, which proves that the **costume** matters. **(Ignore this)**

I have made a new test, to see which fractions give the most glitches:
<a href="https://llk.github.io/scratch-gui/develop/#411621582">and this is thus **result**.</a>

**Comment by RexScratch** [comment]
> K, I noticed this glitch occurred recently and made a forum about it, but thankfully I was given [this link](https://github.com/LLK/scratch-render/issues/642/)!!!
> (Thanks @apple502j). I think that this glitch occurred at the same time the [Fullscreen Glitch](https://scratch.mit.edu/discuss/topic/414997/) Occurred
> 
> ### **EDIT**
> This [link](https://llk.github.io/scratch-gui/develop/#411430200), which I created myself is a test, which proves that the **costume** matters.

The only thing that test shows about costumes is that costumes can affect the sprite's position, which is already well-known.
