### ISSUE TITLE
"touching (sprite)" could be faster

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#663]
Now that we have one central function in which we update CPU render pipeline attributes for a single drawable, we can move the "use nearest neighbor or not" check into that function instead of doing it once per pixel.

**Comment by Explosion-Scratch** [comment]
Ooh, this would be great! It would be awesome to have this be faster, could touching color be faster as well?

**Comment by adroitwhiz** [comment]
It looks like "touching color" also calls `isTouching`, so it will also be improved by #664 (about 50% faster in my testing).

**Comment by Explosion-Scratch** [comment]
@androitwhiz That's super cool! Thanks for working on these! (I actually avoid using touching color a lot because of it's slow speed, I guess I don't have to anymore!)
