### ISSUE TITLE
TypeError with Chrome on Windows 10

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#68]
From a Scratch user:
![](http://image.prntscr.com/image/711a6348981e47d991e7e6de8afd9450.png)

Looking at the code, my initial guess is that there may be a race condition between creation of the WebGL rendering context and attempting to `createBufferFromTypedArray`.

**Comment by SillyInventor** [comment]
I get this error when webgl is not enabled on chrome. Perhaps a check on the index.html page (try and get a webgl context, and catch with popup and stop) would help.

**Comment by rschamp** [comment]
We'll deal with this in the GUI eventually, this is a compatibility issue.
