### ISSUE TITLE
scratch-render tests fail locally on node 12

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#680]
### Expected Behavior
Tests should pass regardless of node version

### Actual Behavior
Tests fail, something about requizzle

### Steps to Reproduce
`npm run test` in scratch-render
<img width="670" alt="Screen Shot 2020-08-20 at 15 43 17" src="https://user-images.githubusercontent.com/2855464/90817879-39592180-e2fc-11ea-8a8c-9094e3a36360.png">

### Operating System and Browser
Mac OSX

**Comment by fsih** [comment]
It's working for @cwillisf on Windows 🤔

**Comment by cwillisf** [comment]
Looks like we just need to update jsdoc so we get a newer requizzle: hegemonic/requizzle#5
