### ISSUE TITLE
Support RGBA for pen

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#73]
Our current pen implementation supports RGBA (albeit in a very hidden way) which is used by many advanced Scratchers.

### Example
https://scratch.mit.edu/projects/125372703
https://llk.github.io/scratch-vm/#125372703

**Comment by cwillisf** [comment]
Moved to LLK/scratch-vm#393: the renderer actually already supports RGBA but it's not exposed at the block level.
