### ISSUE TITLE
Pixely images rendered

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#77]
### Expected Behavior

Image should not be pixely. 

### Actual Behavior

![screenshot 2017-01-27 at 8 57 49 pm](https://cloud.githubusercontent.com/assets/10731781/22393391/82ab595a-e4d3-11e6-9d71-571bb6a748be.png)

### Steps to Reproduce

1. In this case, I opened Scratch GUI but I think it is a rendering issue...
2. Observe the already place scratch cat

### Operating System and Browser

Chromebook latest version

---
Moved from LLK/scratch-vm#405
/cc @CosmicWebServices

**Comment by SillyInventor** [comment]
This is mostly because you're using gl.NEAREST:
![image](https://cloud.githubusercontent.com/assets/8440451/22706761/7e053498-ed3e-11e6-9107-e244c5fa5bbf.png)

 instead of gl.LINEAR:
![image](https://cloud.githubusercontent.com/assets/8440451/22706744/6e525008-ed3e-11e6-96d6-d4a5113ac677.png)

**Comment by SillyInventor** [comment]
Would you like a fix for this?

**Comment by cwillisf** [comment]
I thought I remembered a problem when using nearest-neighbor sampling with the pixelate effect, but I just ran a quick test and I don't see any issue currently. Maybe we should just go ahead and switch to `gl.LINEAR` for the minification filter... we can always address any issues that pop up if and when they do.

The magnification filter is slightly trickier. For bitmap images, it really depends on the image whether you'd want nearest-neighbor or linear filtering. I think the safe move is to stick with nearest-neighbor for bitmap magnification for now.

For vector images the plan is to re-rasterize the image when the scale increases enough to warrant a larger texture. Scratch 2.0 does something similar with good results, and I think it would be even simpler to implement in the new renderer. This is why `getTexture` takes a `scale` argument, for example 😄. Until we get there, though, I think we should use the same magnification filter for both bitmaps and vectors.

I also think we should experiment with mipmaps, but I'm concerned that there might be unexpected side effects with projects that use `touching color` and other, similar features. If we can get away with it, though, mipmaps might provide a benefit to both performance and visual quality.

Summary:
- Sooner: let's try linear filtering for minification in all cases.
- Later: implement on-demand re-rasterizing for vector images and then experiment with mipmaps and linear filtering for magnification of vector images.
- Never(?): use linear filtering on bitmap magnification.

I'd love to hear other opinions on all this, especially if you have a situation where what I've described above ends up looking bad.

**Comment by cwillisf** [comment]
And, of course, right after I posted the above I found the problem I had been remembering.

Here's one situation which causes the problem:
- Bitmap costume
- Set scale to 150%
- Set pixelate effect to 20

This is the result when you have the minification filter set to `gl.LINEAR`:
![image](https://cloud.githubusercontent.com/assets/7019101/22848437/3a48ca7c-efa9-11e6-84c0-cd2b22ec6c40.png)

Scratch 2.0 avoids this problem by turning off linear filtering in very specific cases:
https://github.com/LLK/scratch-flash/blob/296468bdf42cbfa711cc5abd8cb603776986ea2b/src/render3d/DisplayObjectContainerIn3D.as#L518

**Comment by SillyInventor** [comment]
I think you need to apply linear to magnification rather than minification. Mine goes from looking like the top (nearest) to the bottom (linear).

![image](https://cloud.githubusercontent.com/assets/8440451/22850416/1748ba68-efd7-11e6-9a6e-c659ed26c4ce.png)


![image](https://cloud.githubusercontent.com/assets/8440451/22850408/ee36e8ca-efd6-11e6-8740-dbabec94dd75.png)

**Comment by thisandagain** [comment]
This feels like a blocking issue for the preview release. Adding to December milestone. 

/cc @cwillisf @rschamp
