### ISSUE TITLE
scratch on firefox runs slower than chrome

### ISSUE THREAD

**Issue by SmearyThrower** [LLK/scratch-render#957]
### Expected Behavior

_Please describe what should happen_ Scratch runs at the same speed on both chrome and Firefox 

### Actual Behavior

_Describe what actually happens_ scratch projects run at a noticeably slower fps on Firefox than chrome

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://scratch.mit.edu/...'
2. run a game on chrome and Firefox (games with change y really show a difference)
3. See the speed difference

### System Details
Win 10 Firefox 94

_If using one of the Apps please provide the app version and device details, e.g. Scratch 3.0.57, Android 9 on HP x360 Chromebook_

**Screenshots**

**Comment by adroitwhiz** [comment]
Firefox in general appears to be slower than Chrome, and this isn't Scratch's fault. WebGL performance in particular seems to suffer, but most JS stuff performs worse than in Chrome.

If you can provide a specific example project that's particularly laggy in Firefox compared to Chrome, I can try to look into why it's slow and look into the specific parts that are causing the slowdown.

**Comment by BryceLTaylor** [comment]
Closing.  See the comment from @adroitwhiz .
