### ISSUE TITLE
Question while developing

### ISSUE THREAD

**Issue by Norbiros** [LLK/scratch-render#961]
Hello!
I was creating addon for scratch and I found problem. I want to get which sprite player clicked in scene. Something like on click event, but in JS - not in scratch. For example when you click on sprite `Cat`, it will return it id or object and execute some code. I know it is possible, because you can move sprite on scene - it detects which sprite you clicked and it moves it to mouse position.

**Comment by Norbiros** [comment]
I found this `_activateClickHats` - but how i can acces it? `vm._activateClickHats`?

If i understeand good i must create something like this:
`On sprite summon >> add event listener to it >> when it fires - i know which sprite was clicked`

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-gui/blob/develop/src/containers/stage.jsx#L216
