### ISSUE TITLE
SVG WebFont Families DO NOT Import Properly

### ISSUE THREAD

**Issue by AlexDev404** [LLK/scratch-render#975]
### Expected Behavior

Imported SVG with font-family ['Lobster'](https://fonts.google.com/specimen/Lobster) defined in the `<defs>` tag as a stylesheet which was later imported into the Scratch Editor.

#### Attempt 1

```xml
<svg viewBox="0 0 600 80" xmlns="http://www.w3.org/2000/svg" version="1.1">
   <defs>
      <style type="text/css">@import url('http://fonts.googleapis.com/css?family=Lobster');</style>
   </defs>
   <text x="0" y="60" style="font-family: Lobster;font-size: 60pt;">Lobster</text>
</svg>

```

This **did not** work. I then tried using another method which included importing the font directly from the code.

#### Attempt 2

```xml
<svg viewBox="0 0 600 80" xmlns="http://www.w3.org/2000/svg" version="1.1">
   <defs>
      <style type="text/css">
            @font-face {
                font-family: Lobster;
                src: url("https://raw.githubusercontent.com/google/fonts/main/ofl/lobster/Lobster-Regular.ttf");
            }
      </style>
   </defs>
   <text x="0" y="60" style="font-family: Lobster;font-size: 60pt;">Lobster</text>
</svg>

```

This also **did not** work.

### Actual Behavior

Font does not display and reverts back to Times New Roman.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://scratch.mit.edu/'
2. Navigate to ['Create a New Project'](https://scratch.mit.edu/projects/editor/)
3. Import the SVGs linked in this issue (#975) (Costumes > Choose a Costume > Upload Costume)
4. Upload both files attached and see that font does not display correctly in both instances.

### System Details
**The problem occurs in-browser** 

**Google Chrome 100 on Windows 10 21H1**
```c
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
```

**Screenshots**

#### Screenshot 1

<img src="https://user-images.githubusercontent.com/34188635/166160744-a61a9ac3-e9eb-44a3-a8da-abfb6f215fe3.png" width=450px></img>

#### Screenshot 2
<img src="https://user-images.githubusercontent.com/34188635/166160763-44f75852-d621-4265-9596-88ebe0c87a52.png" width=250px></img>

### Attachments
[attempt1.svg](https://user-images.githubusercontent.com/34188635/166160794-4f7e7caf-d524-46b1-85f6-ffee3bf4e0fc.svg)
[attempt2.svg](https://user-images.githubusercontent.com/34188635/166160790-8284cbfc-8a58-421f-b3c7-41f6ef68ec63.svg)

**Comment by BryceLTaylor** [comment]
It is intentional to block network requests from inside SVGs.

**Comment by AlexDev404** [comment]
> @BryceLTaylor 
> It is intentional to block network requests from inside SVGs.

Is there any reason to why this is intentional?

**Comment by apple502j** [comment]
Scratch projects are designed to be entirely sandboxed and not contact external websites.
